### ISSUE TITLE
DATA to Backend failed, after agent restart

### ISSUE THREAD

**Issue by Avatat** [kubernetes-sigs/apiserver-network-proxy#123]
Hello,
In the beginning, I would like to thank you, apiserver-network-proxy team, for your amazing work :)

I use Konnectivity in version 0.0.10 and Kubernetes 1.18.5. Most of the time everything works flawlessly, but when I restart agent's pods, konnectivity-server don't want to switch traffic to the new connections:
```
I0710 13:11:42.881321       1 server.go:293] >>> DATA sent to backend
I0710 13:11:42.952402       1 server.go:498] <<< Received 372 bytes of DATA from agentID d3c1f7ef-4730-4300-964e-2e382af9e484, connID 1
I0710 13:11:42.961352       1 server.go:278] >>> Received 42 bytes of DATA(id=1)
I0710 13:11:42.961521       1 server.go:293] >>> DATA sent to backend
I0710 13:11:47.641175       1 server.go:418] Connect request from agent 3adda35e-94ab-46ae-bd6c-96a8197ff651
I0710 13:11:47.641222       1 backend_manager.go:99] register Backend &{0xc00050e180} for agentID 3adda35e-94ab-46ae-bd6c-96a8197ff651
W0710 13:11:47.909837       1 server.go:451] stream read error: rpc error: code = Canceled desc = context canceled
I0710 13:11:47.909895       1 backend_manager.go:119] remove Backend &{0xc000222480} for agentID 1bf0e057-b131-45b9-bbcb-ab752e9dfef4
I0710 13:11:47.909940       1 server.go:531] <<< Close backend &{0xc000222480} of agent 1bf0e057-b131-45b9-bbcb-ab752e9dfef4
W0710 13:11:51.898482       1 server.go:451] stream read error: rpc error: code = Canceled desc = context canceled
I0710 13:11:51.898535       1 backend_manager.go:119] remove Backend &{0xc0002223c0} for agentID d3c1f7ef-4730-4300-964e-2e382af9e484
I0710 13:11:51.898592       1 server.go:531] <<< Close backend &{0xc0002223c0} of agent d3c1f7ef-4730-4300-964e-2e382af9e484
I0710 13:11:55.825758       1 server.go:278] >>> Received 53 bytes of DATA(id=3)
W0710 13:11:55.825884       1 server.go:291] >>> DATA to Backend failed: rpc error: code = Unavailable desc = transport is closing
I0710 13:11:55.825914       1 server.go:293] >>> DATA sent to backend
I0710 13:11:55.849556       1 server.go:278] >>> Received 53 bytes of DATA(id=3)
W0710 13:11:55.849659       1 server.go:291] >>> DATA to Backend failed: rpc error: code = Unavailable desc = transport is closing
I0710 13:11:55.849691       1 server.go:293] >>> DATA sent to backend
I0710 13:11:56.097642       1 server.go:418] Connect request from agent 8fe505d3-11a8-4f63-9882-8a963ab16273
I0710 13:11:56.097671       1 backend_manager.go:99] register Backend &{0xc00050e240} for agentID 8fe505d3-11a8-4f63-9882-8a963ab16273
I0710 13:11:57.588222       1 server.go:418] Connect request from agent bf37dd3c-8736-484a-b9e6-6806b4b9338a
I0710 13:11:57.588257       1 backend_manager.go:99] register Backend &{0xc00072c300} for agentID bf37dd3c-8736-484a-b9e6-6806b4b9338a
I0710 13:12:00.827480       1 server.go:278] >>> Received 42 bytes of DATA(id=3)
W0710 13:12:00.827593       1 server.go:291] >>> DATA to Backend failed: rpc error: code = Unavailable desc = transport is closing
I0710 13:12:00.827625       1 server.go:293] >>> DATA sent to backend
I0710 13:12:00.850981       1 server.go:278] >>> Received 42 bytes of DATA(id=3)
W0710 13:12:00.851056       1 server.go:291] >>> DATA to Backend failed: rpc error: code = Unavailable desc = transport is closing
I0710 13:12:00.851075       1 server.go:293] >>> DATA sent to backend
I0710 13:12:00.894264       1 server.go:278] >>> Received 53 bytes of DATA(id=3)
W0710 13:12:00.894345       1 server.go:291] >>> DATA to Backend failed: rpc error: code = Unavailable desc = transport is closing
I0710 13:12:00.894376       1 server.go:293] >>> DATA sent to backend
I0710 13:12:05.953939       1 server.go:278] >>> Received 42 bytes of DATA(id=3)
W0710 13:12:05.954051       1 server.go:291] >>> DATA to Backend failed: rpc error: code = Unavailable desc = transport is closing
I0710 13:12:05.954077       1 server.go:293] >>> DATA sent to backend

```
After konnectivity-server restart, everything is going back to normal.

**Comment by cheftako** [comment]
Hi @Avatat, Given KAS <-segment 1-> Konnectivity Server <-segment 2-> Konnectivity Agent. Is segment 1 configured with http-connect, grpc over https or grpc over uds? You can find the answer in the /etc/srv/kubernetes/egress_selector_configuration.yaml file.

**Comment by Avatat** [comment]
I had issues with HTTP and HTTPS protocols: https://github.com/kubernetes/kubernetes/issues/92690

Now I use konnectivity-server and kube-apiserver in one pod together, and they use GRPC over UDS.

**Comment by Jefftree** [comment]
Hello, looking at the logs it seems that the failure is all tied to one request (id=3). Currently, when a connection is broken and re-established while a data transmission is in progress, the entire request data needs to be retransmitted (the apiserver should handle most of these retries).

Do requests made specifically after the agents reconnect exhibit this behavior as well?

**Comment by Avatat** [comment]
Yes. After agents restart (not only reconnect) I lost communication from KAS to cluster services behind Konnectivity tunnel.
After KAS+Konnectivity-server (they are in one pod) restart, everything backs to normal.

**Comment by cheftako** [comment]
Not sure if its the same issue. Trying to reproduce I improved our test infra (https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/124). Set to making two requests with a 10 second delay and restarted the agent between the first and second request. The client clearly gets stuck. Server log is 
'''
I0712 19:38:29.625672 1005356 main.go:349] Starting health server for healthchecks.
I0712 19:38:32.254969 1005356 server.go:426] Connect request from agent 67c5bcd6-2371-4e65-9c78-5405acaf2d93
I0712 19:38:32.255020 1005356 backend_manager.go:99] register Backend &{0xc000122000} for agentID 67c5bcd6-2371-4e65-9c78-5405acaf2d93
I0712 19:38:43.613487 1005356 server.go:204] proxy request from client, userAgent [test-client grpc-go/1.27.0]
I0712 19:38:43.613751 1005356 server.go:237] start serving frontend stream
I0712 19:38:43.615792 1005356 server.go:248] >>> Received DIAL_REQ
I0712 19:38:43.615867 1005356 backend_manager.go:168] pick agentID=67c5bcd6-2371-4e65-9c78-5405acaf2d93 as backend
I0712 19:38:43.616228 1005356 server.go:268] >>> DIAL_REQ sent to backend
I0712 19:38:43.621304 1005356 server.go:477] <<< Received DIAL_RSP(rand=5577006791947779410), agentID 67c5bcd6-2371-4e65-9c78-5405acaf2d93, connID 1)
I0712 19:38:43.621683 1005356 server.go:140] register frontend &{grpc 0xc00037f410 <nil> 0xc0000a61e0 1 67c5bcd6-2371-4e65-9c78-5405acaf2d93} for agentID 67c5bcd6-2371-4e65-9c78-5405acaf2d93, connID 1
I0712 19:38:43.626176 1005356 server.go:286] >>> Received 102 bytes of DATA(id=1)
I0712 19:38:43.626384 1005356 server.go:301] >>> DATA sent to backend
I0712 19:38:43.632061 1005356 server.go:506] <<< Received 261 bytes of DATA from agentID 67c5bcd6-2371-4e65-9c78-5405acaf2d93, connID 1
W0712 19:38:47.109384 1005356 server.go:459] stream read error: rpc error: code = Canceled desc = context canceled
I0712 19:38:47.109619 1005356 backend_manager.go:119] remove Backend &{0xc000122000} for agentID 67c5bcd6-2371-4e65-9c78-5405acaf2d93
I0712 19:38:47.109866 1005356 server.go:539] <<< Close backend &{0xc000122000} of agent 67c5bcd6-2371-4e65-9c78-5405acaf2d93
I0712 19:38:48.126811 1005356 server.go:426] Connect request from agent 137cf0a5-f0e4-4c39-b33d-30ae53134645
I0712 19:38:48.126843 1005356 backend_manager.go:99] register Backend &{0xc0003ae300} for agentID 137cf0a5-f0e4-4c39-b33d-30ae53134645
I0712 19:38:48.635625 1005356 server.go:286] >>> Received 102 bytes of DATA(id=1)
W0712 19:38:48.635909 1005356 server.go:299] >>> DATA to Backend failed: rpc error: code = Unavailable desc = transport is closing
I0712 19:38:48.635997 1005356 server.go:301] >>> DATA sent to backend
'''

**Comment by Avatat** [comment]
Looks very similar :)
If you prepare a fix, I would like to test it on my case, but I will need a Docker image.

**Comment by Jefftree** [comment]
Per https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/108 we removed retrying when server -> agent connections fail. I think the case in both your scenarios is that the same tunnel (and dialer) is used when the first connection is established, as well as throughout the agent disconnect and reconnect phase. The dialer/tunnel will still map to the old agent since we don't do any reconciliation without the retry step. Using a new dialer/tunnel and retrying the request should be the fix, but existing connections have no understanding that their tunnels are broken.

@cheftako @caesarxuchao we should propagate an error to the client if too many `backend.Send()` errors pop up and either force the connection to be dropped or change the backend (https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/master/pkg/server/server.go#L297). This is especially an issue for long lived requests and connections with a large body of data since we don't have the notion of cancelling a request.

**Comment by Avatat** [comment]
@Jefftree, thank you for the explanation!

Probably I don't understand how KAS works and do the requests, but the connection isn't working even when I try to do `kubectl logs pod_name` after konnectivity-agent restart. As I understand, KAS should make a new request/connection through Konnectivity tunnel, but it still can't.
Maybe KAS uses a single connection to do all requests?

**Comment by Jefftree** [comment]
Hmm that's weird. KAS creates a new tunnel for each log request, so it's possible you're running into a different problem. Just confirming, this is GRPC over UDS?

**Comment by Avatat** [comment]
I use below egress configuration:
```
apiVersion: v1
data:
  egress-selector-configuration.yaml: |
    apiVersion: apiserver.k8s.io/v1beta1
    kind: EgressSelectorConfiguration
    egressSelections:
    - name: cluster
      connection:
        proxyProtocol: GRPC
        transport:
          uds:
            udsName: /etc/kubernetes/konnectivity-server/konnectivity-server.socket
kind: ConfigMap
metadata:
  name: egress-config
```
KAS and konnectivity-server containers works in one pod and they share `/etc/kubernetes/konnectivity-server` directory (as emptyDir volume).

**Comment by Avatat** [comment]
I observed one more thing:
After konnectivity-agent restart I'm getting:
```
$ kubectl logs -n kube-system metrics-server-7f6d95d688-4jm9g -f
Error from server: Get https://.../containerLogs/kube-system/metrics-server-7f6d95d688-4jm9g/metrics-server?follow=true: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /etc/kubernetes/konnectivity-server/konnectivity-server.socket: connect: no such file or directory"
```
and:
```
$ kubectl top nodes
Error from server (ServiceUnavailable): the server is currently unable to handle the request (get nodes.metrics.k8s.io)
```
After konnectivity-server container restart, `kubectl logs ...` is now timeouting, and `kubectl top ...` stays the same.

After KAS (hyperkube) container restart, everything backs to normal and both commands work.

**Comment by Jefftree** [comment]
> ```
> $ kubectl logs -n kube-system metrics-server-7f6d95d688-4jm9g -f
> Error from server: Get https://.../containerLogs/kube-system/metrics-server-7f6d95d688-4jm9g/metrics-server?follow=true: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /etc/kubernetes/konnectivity-server/konnectivity-server.socket: connect: no such file or directory"
> ```

If the UDS socket is missing that seems to be an issue with the konnectivity server, before even reaching the step to dial to the agent. Are you observing any restarts/crash loops/errors for the konnectivity server before you intervene manually?

Also noticed you have the -f flag for logs. Was this command ran after the agent reconnect or before? 

> ```
> $ kubectl top nodes
> Error from server (ServiceUnavailable): the server is currently unable to handle the request (get nodes.metrics.k8s.io)
> ```

I was able to reproduce this and this one should be related to the bug described earlier. Will do some more testing to get a fix.

**Comment by zanetworker** [comment]
We saw similar issues, was not sure what causes it. Could this also be related to the `serverCount` ?

**Comment by Avatat** [comment]
@cheftako, @Jefftree, thank you for your effort!
I built konnectivity-server image with @Jefftree change ^ and I think that it solves the issue. Can't wait for the release with the fix :)

**Comment by Avatat** [comment]
But still, it isn't perfect. After some time and few agent restarts, I'm getting:
```
kubectl --kubeconfig config_dar0908prod logs -n kube-system kube-proxy-tx9sp
Error from server: Get https://...:10250/containerLogs/kube-system/kube-proxy-tx9sp/kube-proxy: dial timeout
```
konnectivity-server log:
```
I0715 09:00:25.347103       1 server.go:300] >>> Received 52 bytes of DATA(id=1)
I0715 09:00:25.347148       1 server.go:316] >>> DATA sent to Backend[3ac8054c-a9c5-4116-b43b-e7e1d5fa2e7f]
I0715 09:00:25.370913       1 server.go:522] <<< Received 1070 bytes of DATA from agentID 3ac8054c-a9c5-4116-b43b-e7e1d5fa2e7f, connID 1
I0715 09:00:25.492191       1 server.go:300] >>> Received 176 bytes of DATA(id=2)
I0715 09:00:25.492239       1 server.go:316] >>> DATA sent to Backend[3ac8054c-a9c5-4116-b43b-e7e1d5fa2e7f]
I0715 09:00:25.494067       1 server.go:522] <<< Received 106 bytes of DATA from agentID 3ac8054c-a9c5-4116-b43b-e7e1d5fa2e7f, connID 2
I0715 09:00:25.496732       1 server.go:522] <<< Received 201 bytes of DATA from agentID 3ac8054c-a9c5-4116-b43b-e7e1d5fa2e7f, connID 2
I0715 09:00:25.496825       1 server.go:522] <<< Received 1255 bytes of DATA from agentID 3ac8054c-a9c5-4116-b43b-e7e1d5fa2e7f, connID 2
I0715 09:00:25.496852       1 server.go:522] <<< Received 360 bytes of DATA from agentID 3ac8054c-a9c5-4116-b43b-e7e1d5fa2e7f, connID 2
I0715 09:00:25.496871       1 server.go:522] <<< Received 222 bytes of DATA from agentID 3ac8054c-a9c5-4116-b43b-e7e1d5fa2e7f, connID 2
I0715 09:00:25.496883       1 server.go:522] <<< Received 146 bytes of DATA from agentID 3ac8054c-a9c5-4116-b43b-e7e1d5fa2e7f, connID 2
I0715 09:00:25.496900       1 server.go:522] <<< Received 236 bytes of DATA from agentID 3ac8054c-a9c5-4116-b43b-e7e1d5fa2e7f, connID 2
I0715 09:00:25.496913       1 server.go:522] <<< Received 130 bytes of DATA from agentID 3ac8054c-a9c5-4116-b43b-e7e1d5fa2e7f, connID 2
I0715 09:00:25.496924       1 server.go:522] <<< Received 110 bytes of DATA from agentID 3ac8054c-a9c5-4116-b43b-e7e1d5fa2e7f, connID 2
I0715 09:00:25.496936       1 server.go:522] <<< Received 260 bytes of DATA from agentID 3ac8054c-a9c5-4116-b43b-e7e1d5fa2e7f, connID 2
I0715 09:00:25.496953       1 server.go:522] <<< Received 257 bytes of DATA from agentID 3ac8054c-a9c5-4116-b43b-e7e1d5fa2e7f, connID 2
I0715 09:00:25.496965       1 server.go:522] <<< Received 238 bytes of DATA from agentID 3ac8054c-a9c5-4116-b43b-e7e1d5fa2e7f, connID 2
I0715 09:00:25.496976       1 server.go:522] <<< Received 248 bytes of DATA from agentID 3ac8054c-a9c5-4116-b43b-e7e1d5fa2e7f, connID 2
I0715 09:00:25.496990       1 server.go:522] <<< Received 594 bytes of DATA from agentID 3ac8054c-a9c5-4116-b43b-e7e1d5fa2e7f, connID 2
I0715 09:00:25.497004       1 server.go:522] <<< Received 475 bytes of DATA from agentID 3ac8054c-a9c5-4116-b43b-e7e1d5fa2e7f, connID 2
I0715 09:00:25.497019       1 server.go:522] <<< Received 576 bytes of DATA from agentID 3ac8054c-a9c5-4116-b43b-e7e1d5fa2e7f, connID 2
I0715 09:00:25.497032       1 server.go:522] <<< Received 1074 bytes of DATA from agentID 3ac8054c-a9c5-4116-b43b-e7e1d5fa2e7f, connID 2
I0715 09:00:25.497054       1 server.go:522] <<< Received 1012 bytes of DATA from agentID 3ac8054c-a9c5-4116-b43b-e7e1d5fa2e7f, connID 2
I0715 09:00:25.497067       1 server.go:522] <<< Received 502 bytes of DATA from agentID 3ac8054c-a9c5-4116-b43b-e7e1d5fa2e7f, connID 2
I0715 09:00:25.497083       1 server.go:522] <<< Received 506 bytes of DATA from agentID 3ac8054c-a9c5-4116-b43b-e7e1d5fa2e7f, connID 2
I0715 09:00:25.497096       1 server.go:522] <<< Received 1451 bytes of DATA from agentID 3ac8054c-a9c5-4116-b43b-e7e1d5fa2e7f, connID 2
I0715 09:00:25.497110       1 server.go:522] <<< Received 476 bytes of DATA from agentID 3ac8054c-a9c5-4116-b43b-e7e1d5fa2e7f, connID 2
I0715 09:00:25.497123       1 server.go:522] <<< Received 1895 bytes of DATA from agentID 3ac8054c-a9c5-4116-b43b-e7e1d5fa2e7f, connID 2
I0715 09:00:25.497142       1 server.go:522] <<< Received 476 bytes of DATA from agentID 3ac8054c-a9c5-4116-b43b-e7e1d5fa2e7f, connID 2
I0715 09:00:25.497154       1 server.go:522] <<< Received 27 bytes of DATA from agentID 3ac8054c-a9c5-4116-b43b-e7e1d5fa2e7f, connID 2
I0715 09:00:26.351907       1 server.go:300] >>> Received 53 bytes of DATA(id=1)
I0715 09:00:26.351974       1 server.go:316] >>> DATA sent to Backend[3ac8054c-a9c5-4116-b43b-e7e1d5fa2e7f]
I0715 09:00:26.366149       1 server.go:300] >>> Received 53 bytes of DATA(id=1)
I0715 09:00:26.366193       1 server.go:316] >>> DATA sent to Backend[3ac8054c-a9c5-4116-b43b-e7e1d5fa2e7f]
I0715 09:00:26.387205       1 server.go:522] <<< Received 248 bytes of DATA from agentID 3ac8054c-a9c5-4116-b43b-e7e1d5fa2e7f, connID 1
I0715 09:00:26.388196       1 server.go:300] >>> Received 42 bytes of DATA(id=1)
I0715 09:00:26.388232       1 server.go:316] >>> DATA sent to Backend[3ac8054c-a9c5-4116-b43b-e7e1d5fa2e7f]
I0715 09:00:26.395401       1 server.go:522] <<< Received 225 bytes of DATA from agentID 3ac8054c-a9c5-4116-b43b-e7e1d5fa2e7f, connID 1
I0715 09:00:26.396012       1 server.go:300] >>> Received 42 bytes of DATA(id=1)
I0715 09:00:26.396041       1 server.go:316] >>> DATA sent to Backend[3ac8054c-a9c5-4116-b43b-e7e1d5fa2e7f]
I0715 09:00:27.824330       1 server.go:300] >>> Received 52 bytes of DATA(id=1)
I0715 09:00:27.824384       1 server.go:316] >>> DATA sent to Backend[3ac8054c-a9c5-4116-b43b-e7e1d5fa2e7f]
I0715 09:00:27.873359       1 server.go:522] <<< Received 1070 bytes of DATA from agentID 3ac8054c-a9c5-4116-b43b-e7e1d5fa2e7f, connID 1
I0715 09:00:30.269968       1 server.go:300] >>> Received 52 bytes of DATA(id=1)
I0715 09:00:30.270022       1 server.go:316] >>> DATA sent to Backend[3ac8054c-a9c5-4116-b43b-e7e1d5fa2e7f]
I0715 09:00:30.310916       1 server.go:522] <<< Received 1070 bytes of DATA from agentID 3ac8054c-a9c5-4116-b43b-e7e1d5fa2e7f, connID 1
I0715 09:00:30.927164       1 server.go:217] proxy request from client, userAgent [grpc-go/1.26.0]
I0715 09:00:30.927297       1 server.go:250] start serving frontend stream
I0715 09:00:30.927314       1 server.go:261] >>> Received DIAL_REQ
I0715 09:00:30.927321       1 backend_manager.go:174] pick agentID=3ac8054c-a9c5-4116-b43b-e7e1d5fa2e7f as backend
I0715 09:00:30.927381       1 server.go:282] >>> DIAL_REQ sent to backend
I0715 09:00:32.756866       1 server.go:300] >>> Received 52 bytes of DATA(id=1)
I0715 09:00:32.756915       1 server.go:316] >>> DATA sent to Backend[3ac8054c-a9c5-4116-b43b-e7e1d5fa2e7f]
I0715 09:00:48.186314       1 server.go:300] >>> Received 46 bytes of DATA(id=5)
I0715 09:00:48.186349       1 server.go:316] >>> DATA sent to Backend[3ac8054c-a9c5-4116-b43b-e7e1d5fa2e7f]
...
I0715 09:01:03.242817       1 server.go:300] >>> Received 46 bytes of DATA(id=5)
I0715 09:01:03.242824       1 server.go:316] >>> DATA sent to Backend[3ac8054c-a9c5-4116-b43b-e7e1d5fa2e7f]
I0715 09:01:03.445538       1 server.go:217] proxy request from client, userAgent [grpc-go/1.26.0]
I0715 09:01:03.445695       1 server.go:250] start serving frontend stream
I0715 09:01:03.445712       1 server.go:261] >>> Received DIAL_REQ
I0715 09:01:03.445718       1 backend_manager.go:174] pick agentID=c743ecec-e248-4dea-b61e-1b14110588bf as backend
I0715 09:01:03.445779       1 server.go:282] >>> DIAL_REQ sent to backend
I0715 09:01:08.204758       1 server.go:300] >>> Received 42 bytes of DATA(id=5)
I0715 09:01:08.204798       1 server.go:316] >>> DATA sent to Backend[3ac8054c-a9c5-4116-b43b-e7e1d5fa2e7f]
...
I0715 09:01:13.215334       1 server.go:300] >>> Received 46 bytes of DATA(id=5)
I0715 09:01:13.215341       1 server.go:316] >>> DATA sent to Backend[3ac8054c-a9c5-4116-b43b-e7e1d5fa2e7f]
```

**Comment by zanetworker** [comment]
@Avatat I had the same issue with having the konnectivity-agent as a deployment, turned it into a `daemonset` worked much better, still I didn't get down to why as a deployment it was stuck sometimes.

**Comment by Avatat** [comment]
> @Avatat I had the same issue with having the konnectivity-agent as a deployment, turned it into a `daemonset` worked much better, still I didn't get down to why as a deployment it was stuck sometimes.

Thank you!
I thought the same and I've tried deployment and daemonset too - I didn't see any difference :(

**Comment by Avatat** [comment]
Ok, I found why `kubectl logs` didn't want to work. The reason is simple and obvious - firewall on my nodes, allow traffic to kubelet (10250 TCP) only from KAS network. When Konnectivity tunnel was established to the agent on thenode A, it can't reach kubelet at node B, because the firewall was dropping communication.

**Comment by cheftako** [comment]
> TCP) only from KAS network. When Konnectivity tunnel was established to the agent on node A, it can't reach kubelet at node B, because the firewall was dropping communication.

Yup. We have a nice to have feature files to try to get the traffic to at least be sent to the correct failure zone (and better yest the right node). However there is benefit to not requiring the traffic have to land on the correct node. The most obvious is that as long as traffic doesn't have to land on the right node, then you can kubectl logs the agent, when its having problems.

**Comment by Jefftree** [comment]
Fixed by https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/125

/close
