### ISSUE TITLE
apiserver-network-proxy-push-images job broken

### ISSUE THREAD

**Issue by Jefftree** [kubernetes-sigs/apiserver-network-proxy#132]
https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/apiserver-network-proxy-push-images

Requesting access to cloudbuild logs to debug further (https://github.com/kubernetes/k8s.io/pull/1056)

/cc @cheftako

**Comment by Sh4d1** [comment]
They are viewable here http://storage.googleapis.com/k8s-staging-kas-network-proxy-gcb/logs/log-66bfaf44-b21f-424a-8128-fe6e371d7fcb.txt 

Source : https://kubernetes.slack.com/archives/CCK68P2Q2/p1582047883132500

**Comment by Sh4d1** [comment]
The ID being the one we get permission denied on 😄

**Comment by Sh4d1** [comment]
Looks like we hit a 20min timeout 🤔

**Comment by Sh4d1** [comment]
Changing https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/master/cloudbuild.yaml#L1 to a higher value should fix the issue :)
