### ISSUE TITLE
Allow backend manager to return backend based on agentID

### ISSUE THREAD

**Issue by charleszheng44** [kubernetes-sigs/apiserver-network-proxy#142]
Currently, `BackendManager.Backend()` does not take any input, and can only return a random agent. Sometimes, the server may want to pick up a specific backend, consider the following: 

Agents are located in different network regions, and the IP address is used as the agentID. when the server receives a request, it can choose the right agent based on the IP address.

**Comment by Jefftree** [comment]
One of the main goals of the backend manager is to be able to select different strategies for picking the backend, so definitely +1 for this idea. I think we started with selecting a random backend for simplicity purposes. @caesarxuchao might be able to provide some additional context on incorporating additional backend selection strategies. 

Feel free to send a PR if there's some specific functionality you're looking for.

**Comment by cheftako** [comment]
+1

From the [network proxy KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20190226-network-proxy.md#alternatives-optional), "It may be desirable to allow out of band data (metadata) to be transmitted from the KAS to the Proxy Server." The intent was to extend the [NetworkContext](https://github.com/kubernetes/kubernetes/blob/release-1.19/staging/src/k8s.io/apiserver/pkg/server/egressselector/egress_selector.go#63) and allow the proxy server to then appropriately select the backend based on the metadata. It would certainly make sense to optionally add failure-zone/zone/region information to the request and have the server show preference of backends based on that. One interesting question would then be how the server knows the failure-zone/zone/region of the backend. The easiest option would probably be if the agent sent it as part of the handshake. The alternate would be to have the proxy server look it up from the api-server based on additional data from the agent. One note is that at the time the KEP was written, api-server <-> proxy server communication was done via HTTP Connect. We now also support GRPC over HTTPS and UDS. So we will need solutions beyond the http headers called for in the KEP.

**Comment by cheftako** [comment]
Also feel free to attend cloud-provider SIG or cloud provider extraction WG meetings if you want to discuss this. (Or ping us on the corresponding slack channels)

**Comment by charleszheng44** [comment]
@Jefftree @cheftako thanks for your reply. We use the apiserver-network-proxy(ANP) in our Kubernetes based edge computing framework. In our case, it is very common that edge nodes are spread in different network regions. Therefore, it would be great if ANP can support different proxy strategy (e.g., one agent per node, or one agent per region). 

I have submitted a pr #143 that tries to tackle this problem, please let me know what you think.
