### ISSUE TITLE
Server logs are too verbose

### ISSUE THREAD

**Issue by trawler** [kubernetes-sigs/apiserver-network-proxy#145]
When running konnectivity-server with `logtostderr=true` we found the logs somewhat too verbose.
We would like to have the ability to dial down on the amount of stream logs, especially the ones below:
```
225 server.go:308] >>> Received 42 bytes of DATA(id=1)" component=konnectivity
225 server.go:324] >>> DATA sent to Backend" component=konnectivity
225 server.go:308] >>> Received 42 bytes of DATA(id=1)" component=konnectivity
225 server.go:324] >>> DATA sent to Backend" component=konnectivity
```
However, setting different `--stderrthreshold` levels doesn't seem to have any effect and in the code, these logs are sent as Info level logs: https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/9e6944a352493d11bc5302db36efc88862490ebf/pkg/server/server.go#L308

If there is no special reason for these logs to be set as Info level logs, I'd like to suggest setting these as `klog.Warningf` logs, and would be happy to submit a PR accordingly.

**Comment by cheftako** [comment]
+1,
I know @mvladev is attempting to address this with
https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/112

**Comment by Jefftree** [comment]
Since https://github.com/kubernetes-sigs/apiserver-network-proxy/issues/145 is merged, I'm going to assume this is fixed. Feel free to reopen if there are still issues.

/close
