### ISSUE TITLE
How to establish communication between master node pod and edge node pod

### ISSUE THREAD

**Issue by yanyhui** [kubernetes-sigs/apiserver-network-proxy#187]
There are three lines. One is that the apisever of the master node and the kubelet of the edge node can establish a long connection between the master node and the edge node through ANP. What I want to know is the second line: how does a service pod of the master node establish communication with a service pod of the edge node? The third line: how does the apisever of the master node establish communication with a random service pod of the edge node

**Comment by cheftako** [comment]
Quick preface. When you say edge node, I am assuming you mean a worker node in the cluster. If you mean something more specific we should probably chat. Also worth pointing out https://kubernetes.slack.com/archives/CPS4Z8G8N for these discussions.

> There are three lines. One is that the apiserver of the master node and the kubelet of the edge node can establish a long connection between the master node and the edge node through ANP. 

Things like "kubectl exec" should be able to establish long lived connections between the KAS (Kubernetes APIServer) and something running on an edge node. Its worth remembering that *currently* ANP if for requests originating from the KAS.
(https://github.com/kubernetes/enhancements/tree/master/keps/sig-cloud-provider/2025-extend-konnectivity-for-both-directions should extend this)

> What I want to know is the second line: how does a service pod of the master node establish communication with a service pod of the edge node? 

It doesn't today. As I mentioned above ANP today is for request originating from the KAS. (Side note the proxy agent establishes the tunnel to the proxy server). There are a few possible workarounds. I think the best workaround would be to have the service pod running on the master attempt what it wants to do through the KAS. The KAS already supports things like exec and proxy. (Eg https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/#manually-constructing-apiserver-proxy-urls)

> The third line: how does the apiserver of the master node establish communication with a random service pod of the edge node

The best answer might be to read https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/1281-network-proxy. 
This is complicated. This answer assumes you are using ANP. The KAS starts by looking up the request in the egress selector. This will indicate a mechanism which may include an ANP proxy server with connection info. Assuming it does the KAS will send the request to the ANP Proxy Server based on the egress selector configuration. Assuming the ANP Proxy Server has an appropriate outbound tunnel, it will forward the request over that tunnel. For HA configurations you could use 1 central ANP Proxy Server but I would recommend collocating the KAS with its own ANP Proxy server.

**Comment by yanyhui** [comment]
@cheftako 
Thanks.
