### ISSUE TITLE
Implement official build images for proxy-server and proxy-agent.

### ISSUE THREAD

**Issue by cheftako** [kubernetes-sigs/apiserver-network-proxy#19]
Currently we have no process for generating Open Source official builds. 
We have promoted gcr.io/google-containers but these are not general OSS official builds.

**Comment by Sh4d1** [comment]
@cheftako any docs on how to implement this?

**Comment by Sh4d1** [comment]
We could setup build on GCB and push on `k8s.gcr.io`. I have no clue if there is some requirements though

**Comment by listx** [comment]
Hello @Sh4d1, there is a "let's let K8s subprojects create official images themselves" effort underway here: https://github.com/kubernetes/k8s.io/blob/master/k8s.gcr.io/README.md

There is an umbrella issue tracker for the overall effort here with high-level updates: https://github.com/kubernetes/k8s.io/issues/157#issuecomment-545558520

The #wg-k8s-infra slack channel is the discussion forum for this effort. Please have a look at the links and feel free to reach out to the folks in there if you have more questions. Thanks!

**Comment by Sh4d1** [comment]
Hmm official builds are set up for staging. Not for releases. I'll close this one
/close
