### ISSUE TITLE
What are the application scenarios of ANP in real projects? 

### ISSUE THREAD

**Issue by yanyhui** [kubernetes-sigs/apiserver-network-proxy#190]
What are the application scenarios of ANP in real projects? Edge computing is one of them.

**Comment by cheftako** [comment]
So the original inspiration for ANP was to replace SSH Tunnels.
That covers a particular managed kubernetes scenario.
The idea for this would be the control plane is part of the cloud providers network.
The data plane (the network the cluster/workload) if part of the customers network.
The two networks may not be "routable" and in fact both sides may view that as good.
Obviously the control plane needs to expose a route to the KAS (and proxy server).
However the data plane may not want to expose any routes into that network.
ANP then provides a backdoor for the KAS and only the KAS to access the data plane.

**Comment by yanyhui** [comment]
@cheftako  thank you for zhe answer.

**Comment by aca** [comment]
@cheftako Can you give me some more explanation about how to achieve this? 
```Obviously the control plane needs to expose a route to the KAS (and proxy server).```

**Comment by cheftako** [comment]
> Walter Fender Can you give me some more explanation about how to achieve this?
> > `Obviously the control plane needs to expose a route to the KAS (and proxy server).`

Hard to answer this without understanding your configuration. 
In general there would be a hole in the firewall (and for HA configurations a load-balancer) to give access to the KAS. 
Other control plane resources such as the ETCD server and scheduler would remain protected by the firewall.
I would suggest whatever solution you use to expose your KAS is probably what you should use to expose the ANP Proxy Server.
The ANP Proxy Server exposes 4 ports and the only one which should be exposed for this is the "agent-port".
If you are thinking you should not need to open both the KAS *and* ANP Server I would suggest looking at https://github.com/kubernetes/enhancements/tree/master/keps/sig-cloud-provider/2025-extend-konnectivity-for-both-directions.
