### ISSUE TITLE
When the network is disconnected, how does the master node communicate with the root node through ANP?

### ISSUE THREAD

**Issue by yanyhui** [kubernetes-sigs/apiserver-network-proxy#191]
1. How does ANP transfer the user's request to the specific service of the root node? 2. Does the ANP agent establish a long connection between the master node's apisever and the root node's kubelet for communication? If not, which component of the apiserver root node of the master node communicates? How can HTTP request to the root node access the specific service through the DNAT rule of iptabel? Is there a connection between the Kube proxy of the root node and the apiserver of the master node to access the specific service? 3. What components or processes does the user's HTTP request go through to access the specific services of the root node? 4. In the case of ANP master and root node, how to check the health of cluster root node, pod exception, deletion, insufficient resources of root node, and how to get the master? 5.What is the role of webhook in ANP?

**Comment by yanyhui** [comment]
@cheftako

**Comment by yanyhui** [comment]
@flaper87 @mortent

**Comment by cheftako** [comment]
> 1. How does ANP transfer the user's request to the specific service of the root node? 

So I would generally suggest not using ANP for things running on the root node. We built it as an option and for reasons of symmetry. However most of the time its easier to configure the KAS to have control traffic be put directly onto the network. It is possible to configure a separate ANP Proxy Server/Agent to specifically handle the control plane traffic but generally not worth the trouble. If your asking how to send traffic destined for the data plane/cluster to the root node, this is something we built the system to allow you to prevent. 

> 2. Does the ANP agent establish a long connection between the master node's apisever and the root node's kubelet for communication? If not, which component of the apiserver root node of the master node communicates? How can HTTP request to the root node access the specific service through the DNAT rule of iptable? Is there a connection between the Kube proxy of the root node and the apiserver of the master node to access the specific service? 

See 1.

> 3. What components or processes does the user's HTTP request go through to access the specific services of the root node?

See 1.

> 4. In the case of ANP master and root node, how to check the health of cluster root node, pod exception, deletion, insufficient resources of root node, and how to get the master? 

See 1.

> 5.What is the role of webhook in ANP?

Orthogonal. ANP is part of the routing/network fabric. Webhooks run on top of the routing/network fabric. We tried hard to ensure we have no dependencies on the webhooks, as the webhooks are unlikely to work if we are down and we didn't want to introduce a bootstrapping (chicken&egg) problem.

**Comment by yanyhui** [comment]
@cheftako  2、3、4.The answers to these three questions are not very clear. Please give a detailed explanation. thanks.

**Comment by cheftako** [comment]
> 2. Does the ANP agent establish a long connection between the master node's apisever and the root node's kubelet for communication? If not, which component of the apiserver root node of the master node communicates? How can HTTP request to the root node access the specific service through the DNAT rule of iptable? Is there a connection between the Kube proxy of the root node and the apiserver of the master node to access the specific service? 

As mentioned in 1  we do not suggest using ANP for things running on the root node. If you do decide to set this up, it would depend on how you did it. The obvious option would be to have an agent running on the control plane, connected to a separate ANP Server instance. The KAS would then talk to that ANP Server instance when it needed to make requests of the control plane. In that case the control plane agent would then put the traffic onto the control plane. The Kubelet would not be involved, unless the KAS's request were to the Kubelet. The tunnel is essentially transparent to the client on the KAS, so things like iptables should work as normal.

> 3. What components or processes does the user's HTTP request go through to access the specific services of the root node?

As mentioned in 1  we do not suggest using ANP for things running on the root node. Please see 2.

> 4. In the case of ANP master and root node, how to check the health of cluster root node, pod exception, deletion, insufficient resources of root node, and how to get the master? 

As mentioned in 1  we do not suggest using ANP for things running on the root node. Please see 2.

**Comment by yanyhui** [comment]
@cheftako Thank you for your answer.
1. I want to know what component the management plane is and is it a node of the data plane cluster? Or is it part of a separate cluster? What are the specific components? If there is a node in the data plane cluster, there are some problems such as pod creation, deletion and health check. How is it managed by the cluster?
2. I feel that the management plane can communicate with KAS, which means that it must be a part of the cluster. I want to know how the management plane is managed by the cluster? Pod creation, health examination and other issues.

**Comment by cheftako** [comment]
> 1. I want to know what component the management plane is and is it a node of the data plane cluster? Or is it part of a separate cluster? What are the specific components? If there is a node in the data plane cluster, there are some problems such as pod creation, deletion and health check. How is it managed by the cluster?

The management plane isn't a component. Its the set of things needed to "run" the data plane. So it would consist of the Kube APIServer, Scheduler, Kube Controller Manager, Etcd etc. Whether its a separate cluster is dependent on how your cloud provider decided to configure things. "How is it managed by the cluster?" The mechanisms for cluster reconciliation are well beyond the API Server Network Proxy. In short there are many controllers running in one or more Controller Managers (The Kube Controller Manager at a minimum) Each controller is watching a set of resources for those resources to deviate (usually deviate in a specific manner) from the goal state (generally referred to as the Spec). When this happens the Controller will attempt to reconcile the deviation and perform actions to bring the cluster back into the goal state.

> 2. I feel that the management plane can communicate with KAS, which means that it must be a part of the cluster. I want to know how the management plane is managed by the cluster? Pod creation, health examination and other issues.

The KAS is part of the management plane. The management plane is what controls the cluster. 

> 3. _The KAS would then talk to that ANP Server instance when it needed to make requests of the control plane._,I want to know the detailed process. Can KAS communicate with ANP to transfer customer requests to a specific service interface? Or can the management plane access the interface data of the target data plane?

The KAS is part of the management plane. The management plane is what controls the cluster. If configured to do so, the KAS can communicate through the ANP to send traffic anywhere agents are connected. In a normal configuration the KAS should be the only component in the management plane which can send traffic through the ANP. Anything else in the management plane (Eg a controller)  which wishes to make a request into the data plane, should be doing so by making a request through the KAS.
