### ISSUE TITLE
Publish agent errors as events

### ISSUE THREAD

**Issue by jveski** [kubernetes-sigs/apiserver-network-proxy#196]
Since getting pod logs is dependent on the agent, troubleshooting a disconnected agent is difficult.

One way to address this would be to publish k8s events for agent errors. If folks think this is a good idea I'd be happy to implement.

**Comment by cheftako** [comment]
Happy to discuss. Would not help if you were using https://github.com/kubernetes/enhancements/tree/master/keps/sig-cloud-provider/2025-extend-konnectivity-for-both-directions but thats not a deal breaker. 

Were you thinking the agent wrote to the status on its own Pod resource? Enhancing something like https://github.com/kubernetes/node-problem-detector?

**Comment by jveski** [comment]
I was thinking about creating events for human consumption i.e. by describing the agent pods. But I like your idea of using a condition since it could also be used as a readiness gate. If there are no objections I'll put together a PR.
