### ISSUE TITLE
Can client authenticate both with proxy-server and destination https-test-server?

### ISSUE THREAD

**Issue by liufen90** [kubernetes-sigs/apiserver-network-proxy#200]
In the example, the client only authenticated with proxy-server. In my user case, the client needs to authenticate with destination https-test-server, for example, the client is kubectl, the https-test-server is kube-apiserver. There was one way to solve the problem: I deleted the proxy-server's certs for client. The client only authenticated with https-test-server. It can work, but it is not safe that I deleted the proxy-server's certs.

**Comment by Iceber** [comment]
>  In my user case, the client needs to authenticate with destination https-test-server, for example, the client is kubectl, the https-test-server is kube-apiserver.

@liufen90 Hi, I also encountered this problem, the certificate of kube apiserver(https-test-server) and the certificate of proxy service are different, when I use kubectl, I can't set the certificate of proxy server, how did you deal with this problem?
