### ISSUE TITLE
Kubernetes network proxy e2e tests broken

### ISSUE THREAD

**Issue by Jefftree** [kubernetes-sigs/apiserver-network-proxy#202]
Not sure what happened, e2e tests with network proxy enabled have been failing since 5/7/2021.

https://k8s-testgrid.appspot.com/sig-api-machinery-network-proxy#ci-kubernetes-e2e-gci-gce-network-proxy-http-connect

**Comment by cheftako** [comment]
Seems to have begun failing between 17:49 PDT (Commit 1f3fd1cb8) and 15:49 PDT (Commit a5cf298a9) on May 6th. 
$ git rev-list --ancestry-path a5cf298a9..1f3fd1cb8
1f3fd1cb80fa37bdaa1fd1ee30d35f84681cdd54
Which leads us to https://github.com/kubernetes/kubernetes/commit/1f3fd1cb80fa37bdaa1fd1ee30d35f84681cdd54.
That is pull https://github.com/kubernetes/kubernetes/pull/101751 which lines up on time.

/cc @vinayakankugoyal
