### ISSUE TITLE
serveRecvBackend should not block on sending to frontend.

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes-sigs/apiserver-network-proxy#222]
This is derived from an offline discussion with @cheftako and @jkh52.

For each agent, the proxy server runs a [serveRecvBackend() goroutine](https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/603aa670ea3d1e8449dfc7ddd9a303a07a53b904/pkg/server/server.go#L611) to serve the traffic from the proxy agent to the proxy server.

When debugging #167, we found that the serveRecvBackend can [block](https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/603aa670ea3d1e8449dfc7ddd9a303a07a53b904/pkg/server/server.go#L675) on sending to a frontend if that frontend did not consume the data in the grpc connection and the amount of unread data reached the threshold set by the grpc flowcontrol. This blocked __all__ traffic that was proxied by the proxy agent.

We need to improve the isolation among frontends. A few thoughts we had:
* We can add a timeout on the send. GRPC does not provide a timeout interface, so we have to do this in the form of a select block.
* If sending to a frontend ever times out, proxy server marks this frontend as unhealthy, so that it can skip sending future packets to it to avoid more blocking.
* Unfortunately we can't terminate the GRPC connection from the server side, and in this case, the proxy server is the GRPC server. Thus, the proxy server can only passively wait for the frontend to terminate the GRPC connection. This can lead to memory leaks.
  * What the proxy server can do is that it can mark itself as unhealthy in its `/healthz`, so that kubelet will restart the proxy server, and that resets all broken GRPC connections.
* We can add histogram metrics for the latency of the send as the first step.

**Comment by cheftako** [comment]
> marks this frontend as unhealthy
To be clear we mentioned marking the frontend stream an unhealthy. (As opposed to marking an entire KAS as unhealthy)

**Comment by ydp** [comment]
Hi @caesarxuchao , thanks again for your work, if the purpose of marking proxy-server as unhealthy is to let kubelet restart it, could it be possible to just let it exit and make supervisor to restart it? Per my understanding, the ANP is meant to isolate control plane and cluster network, one way to achieve that is to remove kubelet from control plane, in this case, marking proxy-server unhealthy is not enough to make it restart.

**Comment by caesarxuchao** [comment]
https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/234 adds the histogram metrics.

**Comment by cheftako** [comment]
> Hi Chao Xu , thanks again for your work, if the purpose of marking proxy-server as unhealthy is to let kubelet restart it, could it be possible to just let it exit and make supervisor to restart it? Per my understanding, the ANP is meant to isolate control plane and cluster network, one way to achieve that is to remove kubelet from control plane, in this case, marking proxy-server unhealthy is not enough to make it restart.

So it would certainly be possible to have a flag which told the proxy-server to exit on unhealthy. I see no reason we can't do that, though I'm not sure how often it would be used.

Why not often used? When the control-plane is running separate from the cluster network, its still pretty normal to run the control plane via a kubelet. The relevant kubelet is usually not reading/writing to KAS its controlling. Instead the Kubelet is usually configured statically via manifest files. In this sort of case (or the kubeception case) its perfectly reasonable to return an unhealthy status and let the Kubelet handle it.
