### ISSUE TITLE
Performance of Konnectivity is limited when using proxy requests

### ISSUE THREAD

**Issue by mcginne** [kubernetes-sigs/apiserver-network-proxy#236]
In previous Kube versions we were using OpenVPN, but have switched to Konnectivity for Kube v1.21.

I have been running some performance tests to compare the performance of the 2 providers.

When running proxy requests to hit a service running in the cluster I am seeing much lower performance with Konnectivity:

I am using jmeter with 50 threads to hit the following URL:
```
https://<master URL>/api/v1/namespaces/default/services/http:httpperf-np-service:http/proxy
```
`httpperf-np-service` is a simple http server running in the cluster.

I ran tests comparing OpenVPN and then Konnectivity with different CPU limit settings for the `konnectivity-server` pod. The results are here:

<img width="737" alt="image" src="https://user-images.githubusercontent.com/27362732/121527303-2aaa3b00-c9f2-11eb-994f-c6bbd75647ae.png">

We can see OpenVPN has significantly higher throughput.

On looking at the Konnectivity logs it looks like it is doing a lot of opening and closing of connections to the nodes:
```
0609 16:00:18.218892       1 tunnel.go:121] "Starting proxy to host" host="172.30.80.4:8080"
...
I0609 16:00:18.229134       1 server.go:708] "Received CLOSE_RSP" connectionID=10280
E0609 16:00:18.229169       1 server.go:716] "CLOSE_RSP send to client stream error" err="tls: use of closed connection" connectionID=10280
I0609 16:00:18.229203       1 server.go:260] "Remove frontend for agent" frontend=&{Mode:http-connect Grpc:<nil> HTTP:0xc000868700 connected:0xc00098ede0 connectID:10280 agentID:4af8bf83-1f9a-4261-a0c8-ed7127db5ee2 start:{wall:13846413005822083990 ext:1129737651194 loc:0x21866c0} backend:0xc00020ed20} agentID="4af8bf83-1f9a-4261-a0c8-ed7127db5ee2" connectionID=10280
I0609 16:00:18.229228       1 server.go:721] "Close streaming" agentID="4af8bf83-1f9a-4261-a0c8-ed7127db5ee2" connectionID=10280
```
(Full logs can be found at -> 
[konnectivity-proxy-logs.txt](https://github.com/kubernetes-sigs/apiserver-network-proxy/files/6631460/konnectivity-proxy-logs.txt)

So it looks like OpenVPN may keep the connection open, whereas Konnectivity is opening/closing a connection for each Proxy request - which I suspect will make a significant performance difference. Would it be possible to consider using more persistent connections for Konnectivity?

As background I also ran some tests to make concurrent `kubectl logs` requests to download a 50MB file. Konnectivity shows much better performance than OpenVPN when downloading lots of logs concurrently - but this will be transferring a lot of data over a single connection, whereas the proxy test is making much smaller requests.

**Comment by jkh52** [comment]
Hi - I noticed the logs indicates http-connect mode; I would be interested in whether grpc mode is similar or different, have you tried it?

**Comment by mcginne** [comment]
@jkh52 We haven't tried grpc mode yet, just checking if it's something we can try out..

**Comment by mihivagyok** [comment]
Hi!

When GRPC is configured in the egress selector configuration (for Kube API server), then we need to use UDS. Do I understand right?
apiserver log:
```
Error: failed to validate egress selector configuration: service.connection.uds: Required value: UDS must be set with GRPC
```
https://kubernetes.io/docs/tasks/extend-kubernetes/setup-konnectivity/#configure-the-konnectivity-service
```
# UDS is recommended if the Konnectivity server
# locates on the same machine as the API Server. You need to configure the
# Konnectivity server to listen on the same UDS socket. 
```

I believe this won't work us (I work with @mcginne).

Thank you!
Adam

**Comment by mcginne** [comment]
We tried with GRPC mode, and it only gave a very slight improvement - still well behind the OpenVPN results:
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/27362732/124443884-f8cc9000-dd75-11eb-9dea-359cc97f5c43.png">
