### ISSUE TITLE
Enable more linters by default

### ISSUE THREAD

**Issue by aojea** [kubernetes-sigs/apiserver-network-proxy#244]
It is always hard to get a good set of enabled linters plugins, however, once you get them they are very useful.

Currently there are only 3 linters enabled
https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/5d2b5126a2f0c9640ca0394a0b3b5039fb96210b/Makefile#L85

I've created 2 PRs to add `govet` and `unused`
https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/243
https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/241

I didn't check into much detail, but if I run a `golangci-lint run` I got more errors belonging to the plugins `gosimple`, `statickcheck` and `errcheck`.

It may be useful to go through those errors and understand if they are legit and/or it would be useful to run more linters on CI

**Comment by cheftako** [comment]
Both have been approved and thank you for getting this done!

**Comment by aojea** [comment]
> Both have been approved and thank you for getting this done!

my pleasure :smile:
