### ISSUE TITLE
konnectivity-server.socket  too many open files

### ISSUE THREAD

**Issue by ydp** [kubernetes-sigs/apiserver-network-proxy#256]
In upgrade cluster scenario, we hit issue that reports error in KAS log:

```
E0806 22:46:58.032535       7 egress_selector.go:197] failed to create connection to uds name /var/vcap/data/kubo-apiserver/konnectivity-server.socket, error: dial unix /var/vcap/data/kubo-apiserver/konnectivity-server.socket: socket: too many open files
```
The upgrade path is from k8s 1.19 to 1.20, and related ANP is from v0.0.12 to v0.0.15, but logs came from https://github.com/kubernetes/kubernetes/blob/v1.19.10/staging/src/k8s.io/apiserver/pkg/server/egressselector/egress_selector.go#L197, so we must fail to upgrade, the problematic version should be v0.0.12, however I did not find any related PR that could address this problem

One thing we noticed in kube-apiserver logs is there are many logs like below：

```
I0806 20:36:02.536957       7 trace.go:205] Trace[2147399186]: "Proxy via HTTP Connect over uds" address:10.21.28.39:10349 (06-Aug-2021 20:35:32.535) (total time: 30001ms):
Trace[2147399186]: [30.0011188s] [30.0011188s] END
I0806 20:36:02.536958       7 trace.go:205] Trace[1963171109]: "Proxy via HTTP Connect over uds" address:10.21.28.39:10349 (06-Aug-2021 20:35:32.535) (total time: 30001ms):
Trace[1963171109]: [30.001198999s] [30.001198999s] END
I0806 20:36:02.536982       7 trace.go:205] Trace[1445485052]: "Proxy via HTTP Connect over uds" address:10.21.28.39:10349 (06-Aug-2021 20:35:32.535) (total time: 30001ms):
Trace[1445485052]: [30.001252401s] [30.001252401s] END
I0806 20:36:02.536985       7 trace.go:205] Trace[1719897643]: "Proxy via HTTP Connect over uds" address:10.21.28.39:10349 (06-Aug-2021 20:35:32.535) (total time: 30001ms):
Trace[1719897643]: [30.001286201s] [30.001286201s] END
I0806 20:36:02.537557       7 trace.go:205] Trace[1586683578]: "Proxy via HTTP Connect over uds" address:10.21.28.39:10349 (06-Aug-2021 20:35:32.535) (total time: 30001ms):
Trace[1586683578]: [30.001677004s] [30.001677004s] END
E0806 20:36:02.605020       7 available_controller.go:490] v1beta1.controlplane.antrea.tanzu.vmware.com failed with: failing or missing response from https://10.21.28.39:10349/apis/controlplane.antrea.tanzu.vmware.com/v1beta1: Get "https://10.21.28.39:10349/apis/controlplane.antrea.tanzu.vmware.com/v1beta1": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

And we not only observer massive FD descriptor created, also high memory usage in this circumstance.

Found a similar issue #93 , does this PR fix the issue completely? see #86 comments said that #93 is a temporary solution.

**Comment by rata** [comment]
@ydp this seems somewhat similar to #276, but we only tried with kube 1.21. Do you see this:
a. With a recent konnectivity version and kube 1.19?
 b. With kube 1.19 and konnectivity 0.0.12?
c. Any version of konnectivity with kube 1.20+ does it have this problem?

**Comment by ydp** [comment]
@rata this issue does not reproduce very often for us, will update if we reproduce, thanks.

**Comment by rata** [comment]
@ydp thanks! I'm curious to know if you can reproduce with the steps here: https://github.com/kubernetes-sigs/apiserver-network-proxy/issues/276#issuecomment-967297381

**Comment by andrewsykim** [comment]
@ydp I'm gonna close this PR given the following fixes have merged around this issue:
* https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/328
* https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/337
* https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/339 

If you still continue to see leaking open files after these patches feel free to re-open the issue. Note that some of the patches require updates to kube-apiserver, see https://github.com/kubernetes/kubernetes/pull/108437.

**Comment by andrewsykim** [comment]
Oh you're right, sorry I just assumed it was grpc since we referenced https://github.com/kubernetes-sigs/apiserver-network-proxy/issues/276

**Comment by ydp** [comment]
Just update: this issue is not easy to repro in the first place, and we do not see it recently.

**Comment by rata** [comment]
@ydp Thanks. Can you confirm with which versions you don't see it?

**Comment by ydp** [comment]
The latest version we're using is v0.0.22
