### ISSUE TITLE
too many timeout requests to remote causes tunnel between server and agent hangs

### ISSUE THREAD

**Issue by ydp** [kubernetes-sigs/apiserver-network-proxy#268]
When you have a metrics server that's broken, the APIService request from KAP to metrics server will timeout, in fact, all requests return at code  https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/v0.0.22/pkg/agent/client.go#L390 , which looks good. But this event will cause other requests, like `kubectl exec/logs` to other running pod hangs. I can observe that the other requests sent by ANP server successfully go to this code https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/master/pkg/server/server.go#L435, but on the agent side, I don't observe any requests coming from https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/v0.0.22/pkg/agent/client.go#L355 (except the metrics requests that constantly comes along). After I delete the metrics server APIService, eventually the metrics requests will stop coming, then the tunnel will recovery by itself, then everything works fine. 

Is it possible that the bidirectional stream hangs in this scenario? Any suggestions how to debug this kind of situation? To keep the issue symptom I need the metrics requests sent constantly, but this will disturb me to inspect whether other requests arrive at agent side with tcpdump (cannot identify the packet because the dialAddress is proto format).

I enabled the pprof, but did not find anything useful. Also, the GRPC_TRACE and GRPC_VERBOSITY seems not working for grpc golang version?

**Comment by ydp** [comment]
Added some logs:
server side:
```
func (b *backend) Send(p *client.Packet) error {
	b.mu.Lock()
	defer func(){
		b.mu.Unlock()
		if p.Type == client.PacketType_DIAL_REQ {
			klog.V(5).Infoln("DIAL_REQ sent to backend", p.GetDialRequest().Address, p.GetDialRequest().Random)
		}
	}()
	return b.conn.Send(p)
}
```
agent side:
```
func (a *Client) Recv() (*client.Packet, error) {
	a.recvLock.Lock()
	defer a.recvLock.Unlock()

	pkt, err := a.stream.Recv()
	if err != nil && err != io.EOF {
		metrics.Metrics.ObserveFailure(metrics.DirectionFromServer)
	}

	if pkt.Type == client.PacketType_DIAL_REQ {
		klog.V(5).InfoS("Received packet", "address", pkt.GetDialRequest().Address, pkt.GetDialRequest().Random)
	}
	return pkt, err
}
```
Normally, I can see logs print from both side immediately:
server
```
I0927 03:41:45.955640       6 backend_manager.go:90] DIAL_REQ sent to backend 10.0.16.11:10250 4715263470724098287
```
agent
```
I0927 03:41:45.955326       1 client.go:280] "Received packet" address="10.0.16.11:10250" %!s(int64=4715263470724098287)="(MISSING)"
```
But when the issue happens, it could be seen that the client side received the packet after a very long time (or never received the packet), which caused all requests timeout in 30 seconds with code https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/v0.0.17/konnectivity-client/pkg/client/client.go#L207 
server
```
I0927 03:42:01.772628       6 backend_manager.go:90] DIAL_REQ sent to backend 10.0.16.11:10250 3708040621092176170
I0927 03:42:36.530174       6 backend_manager.go:90] DIAL_REQ sent to backend 10.0.16.11:10250 2295804973744031370
I0927 03:43:24.457455       6 backend_manager.go:90] DIAL_REQ sent to backend 10.0.16.11:10250 6211302547783742573
I0927 03:50:13.693697       6 backend_manager.go:90] DIAL_REQ sent to backend 10.0.16.11:10250 3382728938346140002
I0927 03:51:04.898434       6 backend_manager.go:90] DIAL_REQ sent to backend 10.0.16.15:10250 2491247115562305392
```
agent
```
I0927 03:43:02.318165       1 client.go:280] "Received packet" address="10.0.16.11:10250" %!s(int64=3708040621092176170)="(MISSING)"
I0927 03:44:42.339866       1 client.go:280] "Received packet" address="10.0.16.11:10250" %!s(int64=2295804973744031370)="(MISSING)"
I0927 03:48:02.390080       1 client.go:280] "Received packet" address="10.0.16.11:10250" %!s(int64=6211302547783742573)="(MISSING)"
```
Above first 3 packets are sent in a short time after both server/agent sides restarted (the 3th packet received after a long time it's sent out) , the 4th and 5th packets are sent after like 8 minutes later, then the agent did not (never) receive them. then I deleted the metrics APIService at about `03:55`, still did not receive the packet, then restarted proxy-server at `04:04`, still did not get any packet, instead I get 3 close connection messages (which is expected is the first 3 packets):
```
E0927 04:03:57.580352       1 client.go:502] "connection read failure" err="read tcp 10.0.16.15:46724->10.0.16.11:10250: use of closed network connection" connectionID=2
E0927 04:03:57.581061       1 client.go:502] "connection read failure" err="read tcp 10.0.16.15:47064->10.0.16.11:10250: use of closed network connection" connectionID=3
E0927 04:03:57.581279       1 client.go:502] "connection read failure" err="read tcp 10.0.16.15:47770->10.0.16.11:10250: use of closed network connection" connectionID=4
```
Of course, after delete metrics server and restart proxy-server, everything works fine like described in the first comment.

**Comment by ydp** [comment]
The description that communication eventually recovery by itself after delete metrics server is not accurate, sometimes I never see it recovery.

**Comment by mihivagyok** [comment]
Hi!

Do you use any CPU limit on the agents?

Thank you!
Adam

**Comment by andrewsykim** [comment]
re: https://github.com/kubernetes-sigs/apiserver-network-proxy/issues/268#issuecomment-945233248

Are you able to verify quickly if the agents are close to using their CPU limit? Just to rule out if CPU contention is the issue

**Comment by ydp** [comment]
Hi @andrewsykim this limits is set in our product, and delivery to customer's env for a long time, it does not look like an cause of the issue, this happens because we try to migrate CNI from flannel to Antrea, and when the network partitioned by 2 different networks, the metrics server start to be broken, and eventually causes the ANP hang. 

I can setup a env to reproduce it, but it takes some time.

**Comment by ydp** [comment]
@andrewsykim  btw, are you happen to work on this project on google now? Nice to know that!

**Comment by andrewsykim** [comment]
> I can setup a env to reproduce it, but it takes some time.

This would be useful. Can you share logs from server/agent when you're able to reproduce it?

**Comment by ydp** [comment]
Hi @andrewsykim I reproduced the issue, but I cannot see any info from the logs, please see the attached file.

[proxy-server.stderr.log](https://github.com/kubernetes-sigs/apiserver-network-proxy/files/8087631/proxy-server.stderr.log)

[proxy-agent.log](https://github.com/kubernetes-sigs/apiserver-network-proxy/files/8087633/proxy-agent.log)

**Comment by andrewsykim** [comment]
What's the log level for those logs?
