### ISSUE TITLE
Allow proxy agent to connect to multiple proxy servers.

### ISSUE THREAD

**Issue by cheftako** [kubernetes-sigs/apiserver-network-proxy#30]
Please see https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/1#issuecomment-511925578

We should not need to run 3 proxy agents in each Node for a HA cluster. However we do then want each proxy agent to connect each of the proxy servers.

**Comment by Jefftree** [comment]
This is fixed with https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/46

/close
