### ISSUE TITLE
Do images for proxy-test-client and http-server need to be pushed?

### ISSUE THREAD

**Issue by Jefftree** [kubernetes-sigs/apiserver-network-proxy#306]
Our release pipeline currently pushes images for the proxy-test-client and http-server in additional to the required proxy-server and proxy-agent binaries. We're using the proxy-test-client and http-server strictly for local testing currently, do they need to be pushed to the container registry?

**Comment by cheftako** [comment]
I don't believe so. proxy-test-client and http-server exist specifically to allow us to do testing. So unless our test suites are pulling them in from a reqistry, they should not need to be released.

**Comment by mainred** [comment]
Agree, and I think we don't have customers using proxy-test-client and http-server, or using konnectivity without kubernetes.

**Comment by yue9944882** [comment]
for those who looking for a prebuilt image of {proxy-server,proxy-agent,proxy-test-server/client}, as a workaround we can use `quay.io/open-cluster-management/cluster-proxy:latest` of which the latest release is built over `v0.0.27` of this project.
