### ISSUE TITLE
Are multiple DIAL_REQs valid?

### ISSUE THREAD

**Issue by justinsb** [kubernetes-sigs/apiserver-network-proxy#315]
I was reading through the code, and trying to understand the protocol in use.  I think we're lacking a bit of documentation on the semantics.

First, I think that there are two different protocols, sharing the same messages.  One is for client->server, one is for agent->server.

Also, I think for the client -> server communication, a single DIAL_REQ message must be the first message from the client to the server, and then is not allowed to happen again.  (i.e. there's no multiplexing)

For the agent -> server communication, it looks like multiple DIAL_REQ messages are allowed.

Is that right?  If so, I'd be happy to send a contribution to start adding some docs to the .proto files.

**Comment by cheftako** [comment]
Mostly correct, there are segments for the tunnels, which can each have different protocols. 

Agent -> Server communication is currently always grpc and allows multiple DIAL_REQ messages (multiplexing). 
Client (KAS) -> Server communication is as follows.
- http-connect: uses the http connect verb/standard protocol which only supports a single DIAL_REQ.
- grpc: Theoretically supports multiple DIAL_REQ messages at the protocol level. However for historical reasons the implementation "CreateSingleUseGrpcTunnel" only allows a single DIAL_REQ. This should really be fixed.
