### ISSUE TITLE
Server running with --proxy-strategies=destHost panics even if agent has correct --agent-identifiers

### ISSUE THREAD

**Issue by soider** [kubernetes-sigs/apiserver-network-proxy#316]
If we use "--proxy-strategies=destHost" argument given to the proxy server, the server panics on Connect from the agent.

The problem is in the [pkg/server/server.go:ProxyServer:addBackend](https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/master/pkg/server/server.go#L191) method.

The mentioned method never returns any value for the DestHostManager.

It is workarounded in the fork we use by commit https://github.com/k0sproject/apiserver-network-proxy/pull/5/commits/f4e626bb8bc9150b3ccaed82b4df7513664935c7 but this works only in our specific set up when each agent runs with `--agent-identifiers` argument with only single identifier.

For the case if the `--agent-identifiers` has multiple values, e.g. for host and address, this would not work.

**Comment by mihivagyok** [comment]
@soider Could you please share how do you configure the server and agent?
I understand that there is no return value, and it could be a problem, but I don't see the panic you are reporting.

Do you use the latest version?

Thanks,
Adam

**Comment by mihivagyok** [comment]
Hi! Okay I have tested with only destHost strategy, and it works fine for me. That's why I'm asking. Do you have time to try again with latest versions and post some logs and full config?

Thanks,
Adam
