### ISSUE TITLE
Flatten go mod

### ISSUE THREAD

**Issue by yue9944882** [kubernetes-sigs/apiserver-network-proxy#318]
the replace directive will propagate to any project importing packages from this project. can we converge the konnectivity client package's go mod file with the root?

https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/31f6ed8cbb08a2d16cc80eb3f4344db6354b84fb/go.mod#L57

**Comment by Jefftree** [comment]
What are your use cases for importing packages from the project? Other than konnectivity client, this project was originally designed to run as a standalone binary and not as a library so we have some assumptions baked into the go mod structure. We'd like to keep any imports strictly to the konnectivity client library to avoid the problem you described.

See https://github.com/kubernetes-sigs/apiserver-network-proxy/issues/62#issuecomment-585446782
