### ISSUE TITLE
proxy->agent send stream is blocked due to flow control write quota, leading to goroutine leaks

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes-sigs/apiserver-network-proxy#335]
While investigating https://github.com/kubernetes-sigs/apiserver-network-proxy/issues/276, I ran into anoter goroutine leak on proxy server that can happen when sending messages to a backend.

From the goroutine dump, this was the stack trace for the leaking goroutine:
```
goroutine 476375 [semacquire, 12 minutes]:
sync.runtime_SemacquireMutex(0xc02fa29fb4, 0x1428700, 0x1)
        /usr/local/go/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc02fa29fb0)
        /usr/local/go/src/sync/mutex.go:138 +0x105
sync.(*Mutex).Lock(...)
        /usr/local/go/src/sync/mutex.go:81
sigs.k8s.io/apiserver-network-proxy/pkg/server.(*backend).Send(0xc02fa29fb0, 0xc0113d94c0, 0x0, 0x0)
        /go/src/sigs.k8s.io/apiserver-network-proxy/pkg/server/backend_manager.go:86 +0xb9
sigs.k8s.io/apiserver-network-proxy/pkg/server.(*ProxyServer).serveRecvFrontend(0xc00017bb90, 0x190d458, 0xc02ff7b680, 0xc024e7ea80)
        /go/src/sigs.k8s.io/apiserver-network-proxy/pkg/server/server.go:432 +0xacc
created by sigs.k8s.io/apiserver-network-proxy/pkg/server.(*ProxyServer).Proxy
        /go/src/sigs.k8s.io/apiserver-network-proxy/pkg/server/server.go:367 +0x318
``` 

backend.Send() is lock protected, because we can only call Send() on a stream from a single goroutine (see go docs for SendMsg):

https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/d2eec1ec3ac33f683c81a950f171caab568c0250/pkg/server/backend_manager.go#L85-L89

Upon investigating the rest of the running goroutines, it seems like there are backends from proxy server that were indefinitely blocked due to flow control write quota. This was evident by looking through the goroutine dump and finding this stracktrace:
```
goroutine 468852 [select, 27 minutes]:
google.golang.org/grpc/internal/transport.(*writeQuota).get(0xc00944c0a0, 0xc000004027, 0x3ffb, 0x5)
        /go/pkg/mod/google.golang.org/grpc@v1.27.1/internal/transport/flowcontrol.go:59 +0x7a
google.golang.org/grpc/internal/transport.(*http2Server).Write(0xc02f629080, 0xc00ce65600, 0xc000678000, 0x5, 0x4000, 0xc016258000, 0x4022, 0x4022, 0xc04a32244d, 0x5, ...)
        /go/pkg/mod/google.golang.org/grpc@v1.27.1/internal/transport/http2_server.go:927 +0x1f9
google.golang.org/grpc.(*serverStream).SendMsg(0xc04844f740, 0x1695fe0, 0xc030b1f140, 0x0, 0x0)
        /go/pkg/mod/google.golang.org/grpc@v1.27.1/stream.go:1421 +0x242
sigs.k8s.io/apiserver-network-proxy/proto/agent.(*agentServiceConnectServer).Send(0xc0065f4f80, 0xc030b1f140, 0x4, 0x4)
        /go/src/sigs.k8s.io/apiserver-network-proxy/proto/agent/agent.pb.go:147 +0x49
sigs.k8s.io/apiserver-network-proxy/pkg/server.(*backend).Send(0xc02fa29fb0, 0xc030b1f140, 0x0, 0x0)
        /go/src/sigs.k8s.io/apiserver-network-proxy/pkg/server/backend_manager.go:88 +0x7f
sigs.k8s.io/apiserver-network-proxy/pkg/server.(*ProxyServer).serveRecvFrontend(0xc00017bb90, 0x190d458, 0xc00002c810, 0xc0379fdf20)
        /go/src/sigs.k8s.io/apiserver-network-proxy/pkg/server/server.go:471 +0x10d4
created by sigs.k8s.io/apiserver-network-proxy/pkg/server.(*ProxyServer).Proxy
        /go/src/sigs.k8s.io/apiserver-network-proxy/pkg/server/server.go:367 +0x318
```

From reading this related issue https://github.com/grpc/grpc-go/issues/2427, it seems like the write quota block would happen if the other end of the stream is not calling RecvMsg fast enough, which could happen for various reasons. However, I don't think that leaking goroutines from the proxy server should be the expected behavior in this case. https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/324 might be one potential fix to avoid `backend.Send()` blocking forever, but it may just mask the real problem which is Send() blocking in the first place.

**Comment by mihivagyok** [comment]
This would help the RecvMsg issue, what do you think? https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/310
Thanks!
Adam

**Comment by andrewsykim** [comment]
I'm not sure yet -- one way I reproduced this issue is by setting a really low memory limit on the agent, triggering OOM-kills. My theory is that when agent is OOM-killed the stream is left open and runs out of quota because agent is no longer calling RecvMsg(). I don't know yet why the stream wouldn't just close if agent restarted, especially with server-side keepalives enabled on proxy server. But in any case, it seems like proxy server needs some change to handle when this happens. Maybe https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/324 is the right fix but I need to give it more thought.

**Comment by mihivagyok** [comment]
My experience with the agent limits, that it needs more CPU then memory. If there are many webhooks (e.g. istio), low CPU limit could cause severe issues in the cluster. That's why we don't limit CPU on the agent. But we have memory and CPU limit on the server.

Thank you!

**Comment by andrewsykim** [comment]
> My experience with the agent limits, that it needs more CPU then memory. If there are many webhooks (e.g. istio), low CPU limit could cause severe issues in the cluster. That's why we don't limit CPU on the agent. But we have memory and CPU limit on the server.

True, I guess in the case where agent is CPU limited, https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/310 would be useful
