### ISSUE TITLE
struggling with konnectivity

### ISSUE THREAD

**Issue by parmentelat** [kubernetes-sigs/apiserver-network-proxy#354]
We have resources spanning 2 subnets
A. a production subnet that has public IPs
B. an experimental subnet that is not publicly addressable, and that sits behind a NAT

We have deployed a k8s cluster with its master node on A - following the guidance found in https://kubernetes.io/docs/tasks/extend-kubernetes/setup-konnectivity/

With our current setup it is possible for the nodes in B to join the cluster
also we can spawn and delete pods and containers on the B side as well

However there are at least 2 functions that are problematic:

* `kubectl logs pod-on-the-B-side` if that pod runs on the B side (from either A or B)
* `kubectl exec -ti pod-on-the-B-side -- /bin/bash` if that pod runs on the B side (from either A or B)

in both cases after a timeout we get a message like this one
```
kubectl exec -ti the-pod -- /bin/bash
Error from server: error dialing backend: dial tcp 192.168.3.1:10250: i/o timeout
```

is this the expected behaviour, or else what can we have done wrong ?

**Comment by parmentelat** [comment]
I should have mentioned that 192.168.3.x is, of course, the NAT'ed private address on the the B side

**Comment by andrewsykim** [comment]
> Error from server: error dialing backend: dial tcp 192.168.3.1:10250: i/o timeout

From this error, it seems like the konnectivity agent on B is not able to connect to any of the nodes on B. Kubernetes' log functionality goes through kubelet which is `192.168.3.1:10250`. Can you confirm that networking works between the pod and the node by running `ping`?

**Comment by parmentelat** [comment]
Hi
I have investigated further, and figured out that the konnectivity-agent pod was not properly running on the B node, with this error

```
# k describe pod konnectivity-agent-cwvvn
<snip>
Warning  FailedCreatePodSandBox  3m13s (x84 over 21m)  kubelet            (combined from similar events): 
Failed to create pod sandbox:
 rpc error: code = Unknown desc = failed to create pod network sandbox k8s_konnectivity-agent-cwvvn_blablabla: 
error adding pod kube-system_konnectivity-agent-cwvvn to CNI network "cbr0":
failed to delegate add:
failed to set bridge addr: "cni0" already has an IP address different from 10.244.2.1/24
```

and from the B node's point of view here's the output of
```

ip add show
<snip>
6: flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN group default
    link/ether 22:05:16:fc:fe:d9 brd ff:ff:ff:ff:ff:ff
    inet 10.244.2.0/32 scope global flannel.1
       valid_lft forever preferred_lft forever
    inet6 fe80::2005:16ff:fefc:fed9/64 scope link
       valid_lft forever preferred_lft forever
7: cni0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 36:e5:4e:4f:87:4a brd ff:ff:ff:ff:ff:ff
    inet 10.85.0.1/16 brd 10.85.255.255 scope global cni0
       valid_lft forever preferred_lft forever
    inet6 1100:200::1/24 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::34e5:4eff:fe4f:874a/64 scope link
       valid_lft forever preferred_lft forever
```

Obviously there is something quite wrong in my setup !

Can you please help me make sense out of these messages ?

**Comment by parmentelat** [comment]
I have investigated this further, and found and fixed a couple glitches in our setup along the way (missing rbac configuration was preventing konnectivity deploment; port 8132 was being firewalled from B to A)

at this point what I observe is this
* I rebuilt the cluster from scratch, with one master node on the A side, and one worker node on the B side
* I can check the konnectivity agent gets actually deployed on the B node (it was not making it there yesterday)
* when I try to spawn one user pod (called kiada-fit01) on the B node, it gets stuck at the `ContainerCreating` stage
* and `kubectl describe` on this user pod reports this message
  ```
    Warning  FailedCreatePodSandBox  9m22s                
    kubelet  Failed to create pod sandbox: 
    rpc error: code = Unknown desc = failed to create pod network sandbox k8s_kiada-blablabla): 
    error adding pod kube-system_kiada-fit01-pod to CNI network "cbr0": 
    failed to delegate add: failed to set bridge addr: "cni0" already has an IP address different from 10.244.1.1/24
  ```
* another odd observation is that the IP address that the konnectivity-agent pod receives is in `10.85.0.2` which is totally out of the configured pod-cidr for which I have the usual `podSubnet: 10.244.0.0/16`
* on the B node, the `cni0` interface uses an address in this range too
  ```
  ip add sh cni0 | grep cni0
  6: cni0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
      inet 10.85.0.1/16 brd 10.85.255.255 scope global cni0
  ```

----
I have replayed all this a few times today already, and am not getting consistent results, but this error `failed to set bridge addr: "cni0" already has an IP address different from...` is happening a lot

I could use some help on possible angles to troubleshoot this…
thanks in advance !

**Comment by parmentelat** [comment]
PS

all the nodes involved are set up using fedora35+CRI-O as the container runtime
I have found mentions of the `10.85.0.0` block in the CRI-O repo here
<https://github.com/cri-o/cri-o/blob/main/contrib/cni/10-crio-bridge.conf>

**Comment by parmentelat** [comment]
this is with flannel

**Comment by andrewsykim** [comment]
Is it possible you have two CNIs configured in your cluster by accident?

**Comment by parmentelat** [comment]
mmh, I guess if that was the case I would see the corresponding pods in `kubectl get pods -A` but here's what I have

```
kube-system   coredns-78fcd69978-jzths                      1/1     Running       0          60m
kube-system   coredns-78fcd69978-z96d4                      1/1     Running       0          60m
kube-system   etcd-sopnode-l1.inria.fr                      1/1     Running       15         60m
kube-system   kiada-fit01-pod                               0/1     Terminating   0          57m
kube-system   konnectivity-agent-fv4gw                      1/1     Running       0          59m
kube-system   konnectivity-server-sopnode-l1.inria.fr       1/1     Running       13         60m
kube-system   kube-apiserver-sopnode-l1.inria.fr            1/1     Running       12         60m
kube-system   kube-controller-manager-sopnode-l1.inria.fr   1/1     Running       15         60m
kube-system   kube-flannel-ds-gnzqz                         1/1     Running       0          60m
kube-system   kube-flannel-ds-xwnkk                         1/1     Running       0          60m
kube-system   kube-proxy-7zvj5                              1/1     Running       0          60m
kube-system   kube-proxy-jsz4l                              1/1     Running       0          60m
kube-system   kube-scheduler-sopnode-l1.inria.fr            1/1     Running       15         60m
```

so I would tend to answer no

**Comment by andrewsykim** [comment]
So konnectivity doesn't actually overlap with CNI in anyway. So if you see `FailedCreatePodSandBox` errors on the `kiada-fit01-pod` pod, it seems unrelated to the network proxy and something to do with the CNI configuration of the cluster. 

It seems like you do have pods that are working well though, is it possible that some nodes are misconfigured but others are not? Is `kiada-fit01-pod ` on a different node than the other pods?

**Comment by parmentelat** [comment]
I figured out a piece of the puzzle
what was happening yesterday was that the node on the B side was running a fedora image where `/etc/cni/net.d/` was pre-populated with stuff from the crio rpm

```
# ls -l /etc/cni/net.d/
total 8
-rw-r--r--. 1 root root 438 Mar 15 15:11 100-crio-bridge.conf
-rw-r--r--. 1 root root  54 Mar 15 15:11 200-loopback.conf
# rpm -qf /etc/cni/net.d/*
cri-o-1.22.3-1.module_f35+14123+b0173ecb.x86_64
cri-o-1.22.3-1.module_f35+14123+b0173ecb.x86_64
```

and the `10.85.x.x` thingy that I was seeing was coming from `100-crio-bridge.conf`
removing these files before joining the cluster helped sanitizing things further

---
I'm still experiencing the initial problem though, even if in a slightly different flavour
```
# kubectl logs pod-name
Error from server: Get "https://192.168.3.2:10250/containerLogs/kube-system/kiada-fit02-pod/kiada-fit02-cont": dial tcp 192.168.3.2:10250: i/o timeout
```

**Comment by parmentelat** [comment]
@andrewsykim 
in your initial answer you were saying
> Can you confirm that networking works between the pod and the node by running ping?

not quite sure what you meant there ? pod meaning the konnectivity-agent pod on the B side, right ? and the node I take it would be the NAT'ed address 192.168.3.x ?
also it looks like the konnectivity-agent image has a very low footprint and does not have `/bin/bash` nor `/bin/ping`, so how can I run this test ?

as you can see I am relatively new to kubernetes :-)

thanks for your insight in any case
