### ISSUE TITLE
bug: return 200 when no tunnels available

### ISSUE THREAD

**Issue by mrlihanbo** [kubernetes-sigs/apiserver-network-proxy#355]
The code [here](https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/969e4069465bd4ee932ee7dece4a35a6657c1059/pkg/server/tunnel.go#L81) seems not work. Maybe we can't write response to `w` after Hijacker.

**Comment by jkh52** [comment]
Note: this is http connect, not grpc.
