### ISSUE TITLE
Frontend closing leaks connection

### ISSUE THREAD

**Issue by tallclair** [kubernetes-sigs/apiserver-network-proxy#403]
If the frontend proxy connection is closed after the connection is established (DIAL_RSP received), but before the frontend sends any data packets, then the backend connection would be leaked:

In `serveRecvFrontend`, when the receive loop exits, the function attempts to send a close request to the backend: https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/b5e5436b2fbeaa03657ff2381cef0d46f18ce267/pkg/server/server.go#L526

However, the close request uses `firstConnID`, which is set from the first data packet it receives:

https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/b5e5436b2fbeaa03657ff2381cef0d46f18ce267/pkg/server/server.go#L502

Therefore, if the connection is closed (spontaneously, without sending a `CLOSE_REQ`) before the first data packet is received, then `firstConnID` will be 0, and the backend connection will not be closed.

**Comment by jkh52** [comment]
I believe this is fixed by https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/467
