### ISSUE TITLE
Migrate off github.com/golang/protobuf

### ISSUE THREAD

**Issue by tallclair** [kubernetes-sigs/apiserver-network-proxy#431]
From github.com/golang/protobuf:

> It has been superseded by the [google.golang.org/protobuf](https://pkg.go.dev/mod/google.golang.org/protobuf) module, which contains an updated and simplified API, support for protobuf reflection, and many other improvements. We recommend that new code use the google.golang.org/protobuf module.

We should migrate everything to the newer google.golang.org/protobuf

**Comment by jkh52** [comment]
Fixed by https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/434

(only an indirect dependency remains.)
