### ISSUE TITLE
Difference between v0.1.x and v0.0.x tags

### ISSUE THREAD

**Issue by ipochi** [kubernetes-sigs/apiserver-network-proxy#455]
I'd like to know a bit more about the difference between the two tags and it perhaps a little more documentation is added to explain the same for other users.

As far as I understand v0.1.x branch is the release branch and only bug fixes or something that needs backporting will be cherry picked here and released as a new v0.1.y release ?

The v0.0.x tags continue to be released based of the master branch and when a new feature or something important is added, then a new tag will be released as v0.2.x and continued in the same lieu as above ?

If thats the case, it think it would be nice if we document this somewhere in the md file. I'd be happy to create a PR if my understanding of the tags is correct.

**Comment by jkh52** [comment]
/assign @jkh52 

not a complete answer (RELEASE.md has short explanation), I will add a better markdown proposal soon.
