### ISSUE TITLE
Community meetings and agenda document

### ISSUE THREAD

**Issue by ipochi** [kubernetes-sigs/apiserver-network-proxy#478]
Currently the agenda for the week/meeting notes can be found [here](https://docs.google.com/document/d/1OZE-ub-v6B8y-GuaWejL-vU_f9jsjBbrim4LtTfxssw/edit?usp=sharing).

This covers a broad range pertaining to Kubernetes Cloud Provider Special Interest Group. Its kinda of hard to find out if there was anything related to konnectivity in the recent meetings. Also the video recordings are not available.

Last uploaded video on the [channel](https://www.youtube.com/playlist?list=PL69nYSiGNLP3dXLcYbRKCbpPCN-8CDFAB) is on 31-08-2022.

Since the timing of the meeting (17:00 UTC, biweekly Wednesday) is a little inconvenient for me (22:30 local time), without the video recordings and the agenda document covering a broad area, it makes it a little hard to keep up-to date and continually invested in the upstream community.

I certainly would like to get further involved in the project by addressing issues, creating/reviewing PR(s).

**Comment by cheftako** [comment]
I believe it would make sense to have a regular meeting to go over the issues and pull requests.
Toward that end I would like to get preference on which of the following would work better for everyone.
1) Use the latter part of the [Cloud Provider Extraction]([https://docs.google.com/document/d/1KLsGGzNXQbsPeELCeF_q-f0h0CEGSe20xiwvcR2NlYM/edit](https://www.google.com/url?q=https://docs.google.com/document/d/1KLsGGzNXQbsPeELCeF_q-f0h0CEGSe20xiwvcR2NlYM/edit&sa=D&source=calendar&ust=1680821788074085&usg=AOvVaw21_PFJ0aihZ6119yvY6721) meeting.
2) Start a more specific sub project meeting on Fridays at 10am pacific.

**Comment by jkh52** [comment]
> I believe it would make sense to have a regular meeting to go over the issues and pull requests. Toward that end I would like to get preference on which of the following would work better for everyone.
> 
> 1. Use the latter part of the [Cloud Provider Extraction]([https://docs.google.com/document/d/1KLsGGzNXQbsPeELCeF_q-f0h0CEGSe20xiwvcR2NlYM/edit](https://www.google.com/url?q=https://docs.google.com/document/d/1KLsGGzNXQbsPeELCeF_q-f0h0CEGSe20xiwvcR2NlYM/edit&sa=D&source=calendar&ust=1680821788074085&usg=AOvVaw21_PFJ0aihZ6119yvY6721) meeting.
> 2. Start a more specific sub project meeting on Fridays at 10am pacific.

I like #2 better.

**Comment by ipochi** [comment]
I agree.  Option 2 for me.

**Comment by cheftako** [comment]
Sent out an invite to the meeting to SIG Cloud Provider for 10am Pacific this Friday.

This is the biweekly meeting for the API Server Network Proxy subproject under SIG Cloud Provider.
We will be going over [Issues](https://www.google.com/url?q=https://github.com/kubernetes-sigs/apiserver-network-proxy/issues&sa=D&source=calendar&ust=1681245965289411&usg=AOvVaw0vtI8tQ9oSL9-fhiPdDfi8) and [PRs](https://www.google.com/url?q=https://github.com/kubernetes-sigs/apiserver-network-proxy/pulls&sa=D&source=calendar&ust=1681245965289411&usg=AOvVaw0FlfBLSe4HY5nfVz04nHNa).

Zoom: [https://zoom.us/j/551547753](https://www.google.com/url?q=https://zoom.us/j/551547753&sa=D&source=calendar&ust=1681245965289411&usg=AOvVaw2C-xeOuH09L6Gpt7FGcMch)

**Comment by ipochi** [comment]
@cheftako 

As discussed in the first community call, here is my preferred timing.

Monday or Wednesday 09:00 PT -> Corresponding 21:30 IST. 

Anything before 09:00 PT on Monday or Wednesday works as well.

**Comment by ipochi** [comment]
@cheftako @jkh52 @tallclair 

Can we finalize on the time for the recurring meeting and possibly also an agenda document, that we could have it updated before the meeting so the meeting is structured ?

I'd like to help by creating a new agenda document similar to the existing one if all agree.

**Comment by cheftako** [comment]
How about a 1 off 09:00 next Monday (since we missed several opportunities around KubeCon) and then switch to 09:00 Wednesdays on the SIG Cloud Provider "off" weeks?

**Comment by ipochi** [comment]
Will the meeting link remain the same as the one in earlier comments ?

**Comment by ipochi** [comment]
Ah, I joined this Monday. I think the one-ff was last week I suppose ?

**Comment by cheftako** [comment]
Invites have been sent out to SIG Cloud Provider. They are 9am US pacific alternating with the core SIG Cloud Provider meeting.
