### ISSUE TITLE
konnectivity-agent - improve readiness probe

### ISSUE THREAD

**Issue by mihivagyok** [kubernetes-sigs/apiserver-network-proxy#491]
**What would you like to be added:**

Readiness probe returns OK but it does not consider the actual state/readiness:
https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/master/cmd/agent/app/server.go#L107

This could shall be improved by reporting based on the fact that the agent is connected or not to the server.
- "Ready" - agent is connected successfully to the server
- "Not Ready" - agent fails to connect to the server

**Why is this needed:**

We see cases when agents are not able to connect to the konnectivity server due network issues (e.g. firewall, ACL, etc), but agents are still reporting "ready" status and it gives the false idea that everything is fine with the agent. With this enhancement, we could see easier problems like that.

**Comment by mihivagyok** [comment]
Hi @jkh52 !

Thank you very much for your feedback.
I think any improvement is useful at this time. So I would vote that the konnectivity-agent shall report notReady if not connected at all.

Can you elaborate a bit how konnectivity-server exposes the agent presence signal?

Thank you!
Adam

**Comment by jkh52** [comment]
> Can you elaborate a bit how konnectivity-server exposes the agent presence signal?

Yes - see konnectivity-server [readiness logic](https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/48f7e0fec416cc2f19bbd6a88552075ca3b90fc8/pkg/server/readiness_manager.go#L29-L31)

**Comment by jkh52** [comment]
Despite the ambiguity around the open questions, overall I am +1 on this idea, and the simpler logic (at least 1 agent:server connection) has the pros: 1. simpler 2. similar to konnectivity-server readiness 3. still meets the basic given use case (signal that a user may need to debug firewall rules, etc).

@cheftako WDYT overall, and if we proceed do you think this proposal requires a new agent flag (and keep old behavior as default)?

**Comment by ipochi** [comment]
@jkh52 @mihivagyok @cheftako 

What do you think about this ?
https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/485

**Comment by ipochi** [comment]
The open PR #485 Is good to be merged, if someone other than me can test it out and evaluate whether its meets the requirements discussed above.

**Comment by mihivagyok** [comment]
@ipochi @jkh52 
Thank you very much! Today I was able to test it and it works well for my scenarios.

If you want, I could share some details tomorrow about the test.
Thank you!
Adam

**Comment by ipochi** [comment]
Closing as this is addressed via feature in #485
