### ISSUE TITLE
Need reference high available architecture for konnectivity setup

### ISSUE THREAD

**Issue by jiuchen1986** [kubernetes-sigs/apiserver-network-proxy#502]
Currently each konnectivity agent can only connect to a single konnectivity server which makes the konnectivity server a single failure point. One option is using VIP to fail over between multiple server instances, but still the server would become the bottleneck as the cluster getting larger. Unfortunately the classic loadbalancing method won't work in-between agents and servers. There maybe edge case that one konnectivity server has no agent connected so it's actually unreachable from control plane to worker side through it, while it's not easy for apiservers to be aware of that.

Therefore, it would be good if there is kind of enhancement for the HA scenario that also support loadbalancing.

**Comment by liangyuanpeng** [comment]
May releated: https://github.com/kubernetes-sigs/apiserver-network-proxy/issues/394
