### ISSUE TITLE
Proposal: repo branching

### ISSUE THREAD

**Issue by jkh52** [kubernetes-sigs/apiserver-network-proxy#510]
Currently, [README.md](https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/master/README.md#releases) specifies exactly two well-known version tag ranges (`0.1.*` for kubernetes 1.27+ and `0.0.*` for prior).

Problems:
* The decision to cut a new branch (and new tag minor version) is "as needed" and ambiguous.
* There remains compatibility matrix ambiguity

I propose we switch the version tag scheme to map minor versions 1:1 with kubernetes.

(Inspiration: [client-go](https://github.com/kubernetes/client-go#versioning))

> **Versioning**
> For each v1.x.y Kubernetes release, the major version (first digit) would remain 0.
>
> Bugfixes will result in the patch version (third digit) changing. PRs that are cherry-picked into an older Kubernetes release branch will result in an update to the corresponding branch in client-go, with a corresponding new tag changing the patch version.

Active branches and maintenance policy in this repository would follow kubernetes supported versions range.

**Comment by ipochi** [comment]
> 

I agree. The extra chore can be split in a round robin order amongst those involved in the release (not sure I am a part of the release process yet, but count me in)

**Comment by elmiko** [comment]
i generally agree with the sentiments here, it's a little more hassle/work to do all the cherry-picking and backporting but worth it imo for the clarity. i like that we are drafting off of client-go's pattern as well.

**Comment by elmiko** [comment]
we discussed this topic at the meeting today and since there are no objections, we are going to move forward with the plan proposed here.

/close
