### ISSUE TITLE
release version 0.1.4

### ISSUE THREAD

**Issue by jkh52** [kubernetes-sigs/apiserver-network-proxy#512]
We should tag a new version: 0.1.4.

Changes since 0.1.3: https://github.com/kubernetes-sigs/apiserver-network-proxy/compare/v0.1.3...master

Noteworthy:

* [#494](https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/494) (proxy-server and proxy-agent): quiet more error logs
* [#498](https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/498) proxy-server: change --delete-existing-uds-file default to true.
* [#505](https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/505) (proxy-server and proxy-agent): bump k8s dependencies to 1.27
* [#485](https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/485) proxy-agent: smarter readiness check
* [#511](https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/511) proxy-server: fix broken metric frontend_write_duration_seconds

**Comment by ipochi** [comment]
@jkh52 I'd like a walkthrough of the process when you cut a new release. I'm happy to pick up the next tag release.

**Comment by jkh52** [comment]
> @jkh52 I'd like a walkthrough of the process when you cut a new release. I'm happy to pick up the next tag release.

I follow the steps at [RELEASE.md](https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/master/RELEASE.md), and there shouldn't be anything not documented there or mysterious.

I think only repository admins have the permissions needed to create tags or branches. I have not yet done steps 2 or 3, would you like to do those for 0.1.4?

(For 0.1.3: step 2 was only [just merged](https://github.com/kubernetes/k8s.io/pull/5686), and I never started step 3. I think it's ok to leapfrog from 0.1.2 to 0.1.4 in kubernetes at head.)

**Comment by Nox-404** [comment]
Hey,
I noticed the v0.1.4 tag is present, but the image hasn't been published
https://explore.ggcr.dev/?repo=registry.k8s.io%2Fkas-network-proxy%2Fproxy-agent

**Comment by jkh52** [comment]
> I noticed the v0.1.4 tag is present, but the image hasn't been published

Yes, it's a human trigger so the steps have some delay.

/assign @ipochi 

@ipochi do you want to take steps 2 and 3 (step 2 is the images publish mentioned here)? If you don't have time, please assign back to me.

**Comment by ipochi** [comment]
Sure. I'll look at it in the morning.

**Comment by ipochi** [comment]
Done:

https://github.com/kubernetes/k8s.io/pull/5731
https://github.com/kubernetes/kubernetes/pull/120029

**Comment by ipochi** [comment]
@jkh52 

Why are the steps mentioned in [RELEASE.md](https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/master/RELEASE.md) not idempotent ?

```
./hack/pin-dependency.sh sigs.k8s.io/apiserver-network-proxy/konnectivity-client v0.1.4
./hack/update-codegen.sh
./hack/update-vendor.sh
```

**Comment by jkh52** [comment]
FYI today I made some additional release progress, put notes in https://github.com/kubernetes-sigs/apiserver-network-proxy/issues/523.

**Comment by jkh52** [comment]
No more actionable here.
