### ISSUE TITLE
make release-0.29 branch consistent with k/k libs

### ISSUE THREAD

**Issue by jkh52** [kubernetes-sigs/apiserver-network-proxy#562]
We should do the same as https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/551, for release-0.29 branch. It currently uses [client-go v0.27.4](https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/release-0.29/go.mod#L18C19-L18C26), but should use a v0.29 version.

**Comment by jkh52** [comment]
https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/549 does this for `master` branch. @liangyuanpeng, can you rebase it? We can probably cherry pick the same commit to `release-0.29`.

**Comment by liangyuanpeng** [comment]
I'm back from vacation and let me work for it.

/assign
