### ISSUE TITLE
Ensure webhook availability during Konnectivity Agent rolling update

### ISSUE THREAD

**Issue by dippynark** [kubernetes-sigs/apiserver-network-proxy#566]
We are running Gatekeeper as a validating webhook on GKE (although I don't think the webhook implementation or cloud provider matters) and we have a test where we perform a rolling update of Gatekeeper while continuously making Kubernetes API requests that should be rejected to ensure requests/connections are being drained properly.

However, if we also delete Konnectivity Agent Pods while rolling Gatekeeper (gradually, to ensure that the Konnectivity Agent Pods aren't all down at the same time) or perform a rolling update (`kubectl rollout restart deployment -n kube-system konnectivity-agent`) then a few requests are allowed through (the `ValidatingWebhookConfiguration` is configured to fail open).

My question is whether this is an issue or whether Konnectivity Agent is behaving as expected? I guess this is happening because the long-lived HTTP keepalive connections between the Kubernetes API server and Gatekeeper (via Konnectivity Server and Konnectivity Agent) are being broken when Konnectivity Agent terminates and are not being drained properly (because there is no way for Konnectivity Agent to inspect the encrypted requests and disable keepalive before shutting down).

Should the Kubernetes API server be able to detect such TCP disconnects and retry validation after reconnecting?

**Comment by dippynark** [comment]
@jkh52 In general we try to configure all cluster workloads to gracefully handle being evicted and rescheduled to a different node without any user impact, just to make it easy for us to change infrastructure configuration without users noticing. Specifically for Konnectivity Agent, we would like to avoid API server requests being unexpectedly rejected (when using fail closed webhooks) or unexpectedly accepted (when using fail open webhooks).

The following are the most common scenarios that would cause Konnectivity Agent to be evicted/rescheduled (and therefore could cause a potential webhook request failure):

- Cluster scale down (as you mentioned)
- Google reclaiming a compute instance (we are heavy users of spot VMs so this happens regularly)
- Changing the machine type of a node pool
- Upgrading a node pool
- Upgrading Konnectivity Agent

As you said, we can take steps to reduce the chance of Konnectivty Agent being evicted/rescheduled but we should expect failures under normal operation, so I think this issue can be closed unless there is any value in keeping it open

**Comment by jkh52** [comment]
Thanks for providing details. Sounds good, I will close this.

**Comment by jkh52** [comment]
Re-opening to track potential improvements around agent shutdown.

There is a fairly wide time interval between an agent's first SIGTERM and final termination (terminationGracePeriodSeconds 
 defaults to 30s). [reference](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination)

The historical decision has been for agents stay connected to servers during this time, and continue routing data packets.

The [protocol](https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/7438a96bc2da1cf43e1c9aa090e5643d8dac198e/konnectivity-client/proto/client/client.proto#L26-L33) could be extended to allow a given `konnectivity-agent` to tell `konnectivity-server` that it should be considered "draining". New dials should prefer non-draining agents.

**Comment by dippynark** [comment]
@jkh52 This would be amazing! An alternative would be to deploy Konnectivity Agent as a static kubelet Pod and dialing the Konnectivity Agent only on the Node where the target Pod is running so that the Pod can drain connections when the Node is drained before Konnectivity Agent is terminated (I guess similar to how GKE used to do with the SSH daemon), but I believe this would have scalability issues for large clusters

**Comment by jkh52** [comment]
@dippynark Note that kube-apiserver re-uses established proxy TCP connections up to a certain TTL period. If your webhook calls are frequent enough, we should expect this case. So the proposal is not "airtight", since konnectivity-server agent selection is (initial) dial-time only.

The konnectivity-client library gives kube-apiserver a net.Conn object, so it is difficult to support "will Close() soon" semantics there.

References: [DialContext](https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/master/konnectivity-client/pkg/client/client.go#L42) and [conn.go](https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/master/konnectivity-client/pkg/client/conn.go#L38-L40)

**Comment by dippynark** [comment]
@jkh52 speaking to Google support, they closed my ticket related to this issue because a Google engineer on GitHub (which I am assuming is you) wanted to continue on GitHub.

Google support said there were workarounds for this issue, which I guess is referring to the your [previous comment](https://github.com/kubernetes-sigs/apiserver-network-proxy/issues/566#issuecomment-1949444255); I wouldn't really say they are workarounds, they just reduce the chance of the issue occurring, however happy for this ticket to be closed as I agree that supporting the suggested protocol improvements would be complex and even implementing retries at the API server sounds tricky due to the multiple TCP hops from API server to webhook Pod(s).

We will likely also do the following to reduce the impact of this issue:

- Fail closed when cluster stability wouldn't be impacted
- Implement controllers to apply corrective controls for any invalid changes that get through fail open webhooks

**Comment by jkh52** [comment]
Your plan sounds good, especially in the near term, since OSS improvements will take a while to rollout to GKE (likely introduced in a minor version e.g. 1.30 or 1.31). I will still take a look at this low hanging fruit idea.

**Comment by paulgmiller** [comment]
I think I maybe ran into a fun example of this where we have a an eviction webhook. kubectl drain would work fine until the konnectivityp-agent it was proxying requests through was evicted (there as another konnecitivy agent up and ready). Would get an EOF that stopped kubectl drain

Other drainers will retry and be fine but I thought it was an interesting example of how konnectiivty not draining out its proxies connections can unexpectedly break webhooks. I have a work around but wanted to hopefully give @jkh52  some motivation and thanks for the work he's doing

**Comment by ipochi** [comment]
I think this is an interesting problem as webhooks can be anything from the customer end.

@jkh52 is there updates on  #584 for the server side. Should we open a new issue for the same ?
@paulgmiller Would love to hear your workaround ?

Does having an "eviction order" make sense for such a use case ? Where pod spec has an eviction order that the kubelet follows whne draining the pods ?

**Comment by paulgmiller** [comment]
I gave up on the webhook and am using other signals. SO no help here.
