### ISSUE TITLE
Release new v0.1.x and 0.29.x to pick CVEs and features

### ISSUE THREAD

**Issue by mihivagyok** [kubernetes-sigs/apiserver-network-proxy#574]
https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/569
https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/573
https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/564
https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/568

I can help with testing or with additional PRs if necessary. Thanks!
```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
- [x] creat tag v0.1.8
- [x] create tag v0.28.4
- [x] create tag v0.29.1
- [x] create branch release-0.30
- [x] create tag v0.30.0
- [x] create tag v0.30.1
- [x] create tag v0.30.2
- [x] promote images
```

```[tasklist]
### Tasks
```

**Comment by jkh52** [comment]
For release-0.1 let's block on https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/573 before tag v0.1.8

release-0.28 looks ok to tag v0.28.4

release-0.29 is ok to tag v0.29.1 but it will not include several changes that are only in master (plenty of test improvements, maintenance, but notably changing container images to nonroot variant). If we were to backport that feature, let's block on https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/568. @mihivagyok is that your expectation, that we will wait for v0.30.x?

**Comment by jkh52** [comment]
Tag v0.1.8 is created.

**Comment by mihivagyok** [comment]
Hi @jkh52 ! Thanks!

My expectation is that we can include the listed changes above in the next versions.
If I need to cherry-pick to release branches, I can create the PRs.

We will start using Kubernetes 1.30 soon, so my expectation is that there will a new release v0.30.x.

Thanks!
Adam

**Comment by jkh52** [comment]
> We will start using Kubernetes 1.30 soon, so my expectation is that there will a new release v0.30.x.

Agreed, this repo should soon create release-0.30 branch (from master) and release a v0.30.0. Some process details are unclear: there is not yet a (non-alpha) [client-go](https://github.com/kubernetes/client-go/tags) v0.30.0 tag.

> If I need to cherry-pick to release branches, I can create the PRs.

If you feel something in `master` belongs in v0.29.x range, please open cherry pick PRs to `release-0.29` branch. But, for example, the nonroot variant change seems unjustified to backport, since it may break some users.

**Comment by jkh52** [comment]
@mihivagyok I created tags: v0.28.4, v0.29.1, and v0.30.0.

v0.30.0 introduces your change https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/564

**Comment by mihivagyok** [comment]
Thank you very much @jkh52 !

**Comment by jkh52** [comment]
Sent https://github.com/kubernetes/k8s.io/pull/6554 for image promotion.

**Comment by jkh52** [comment]
Recent batch of release overhead is finished. We can open new tracking issues as needed.

**Comment by mihivagyok** [comment]
Thank you very much!
