### ISSUE TITLE
Rationale behind xfrChannelSize set to const value of 10 and 150

### ISSUE THREAD

**Issue by ipochi** [kubernetes-sigs/apiserver-network-proxy#586]
I'd like to understand the reasons for choosing `const xfrChannelSize = 150` in [pkg/agent/client.go](https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/bd2c976dcfc2dea2fb89a17da314efcb87a0354b/pkg/agent/client.go#L46) and `const xfrChannelSize = 10` in [pkg/server/server.go](https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/bd2c976dcfc2dea2fb89a17da314efcb87a0354b/pkg/server/server.go#L50)

I see a lot of logs in the konnectivity-server with 
```
I0315 11:16:53.457102       1 server.go:853] "Receive channel from agent is full" agentID=0x15e8e00
I0315 11:16:53.457420       1 server.go:853] "Receive channel from agent is full" agentID=0x15e8e00
I0315 11:16:53.457882       1 server.go:853] "Receive channel from agent is full" agentID=0x15e8e00
I0315 11:16:53.458218       1 server.go:853] "Receive channel from agent is full" agentID=0x15e8e00
I0315 11:16:53.458260       1 server.go:853] "Receive channel from agent is full" agentID=0x15e8e00
I0315 11:16:53.458283       1 server.go:853] "Receive channel from agent is full" agentID=0x15e8e00
I0315 11:16:53.458292       1 server.go:853] "Receive channel from agent is full" agentID=0x15e8e00
I0315 11:16:53.458301       1 server.go:853] "Receive channel from agent is full" agentID=0x15e8e00
I0315 11:16:53.458317       1 server.go:853] "Receive channel from agent is full" agentID=0x15e8e00
I0315 11:16:53.458328       1 server.go:853] "Receive channel from agent is full" agentID=0x15e8e00
I0315 11:16:53.458340       1 server.go:853] "Receive channel from agent is full" agentID=0x15e8e00
I0315 11:16:53.458361       1 server.go:853] "Receive channel from agent is full" agentID=0x15e8e00
I0315 11:16:53.458382       1 server.go:853] "Receive channel from agent is full" agentID=0x15e8e00
I0315 11:16:53.458402       1 server.go:853] "Receive channel from agent is full" agentID=0x15e8e00
I0315 11:16:53.458419       1 server.go:853] "Receive channel from agent is full" agentID=0x15e8e00
I0315 11:16:53.458432       1 server.go:853] "Receive channel from agent is full" agentID=0x15e8e00
I0315 11:16:53.458452       1 server.go:853] "Receive channel from agent is full" agentID=0x15e8e00
I0315 11:16:53.458959       1 server.go:853] "Receive channel from agent is full" agentID=0x15e8e00
I0315 11:16:53.459348       1 server.go:853] "Receive channel from agent is full" agentID=0x15e8e00
I0315 11:16:53.459738       1 server.go:853] "Receive channel from agent is full" agentID=0x15e8e00
I0315 11:16:53.460080       1 server.go:853] "Receive channel from agent is full" agentID=0x15e8e00
I0315 11:16:53.460875       1 server.go:853] "Receive channel from agent is full" agentID=0x15e8e00
```

What are my options to improve ? Make the xfrChannelSize configurable via the cli flag ? I'd like to know some historical context as to what thoughts were put into this value? 

Also correct me if I'm wrong if the above `xfrChannelSize` has everything/nothing to do with the above log.

//cc @jkh52 @cheftako

**Comment by jkh52** [comment]
@cheftako do you think this history could be a discussion for the next OSS biweekly? I remember some of the history here but you have the most context.
 
/assign @cheftako

**Comment by jkh52** [comment]
The meeting on 2024-03-20 discussed this topic. (@cheftako can you find the recording link?)

@ipochi do you want to pursue adding flags to support changing these values?

/assign @ipochi

**Comment by cnvergence** [comment]
I have found the same issue, any progress on this one?
Can I help with this topic?

**Comment by cnvergence** [comment]
I would like to work on it, I would be able to open PR soon

**Comment by ipochi** [comment]
Closing this as this is now configurable. Thanks @cnvergence

**Comment by adberger** [comment]
> The meeting on 2024-03-20 discussed this topic. (@cheftako can you find the recording link?)
> 
> 
> 
> @ipochi do you want to pursue adding flags to support changing these values?
> 
> 
> 
> /assign @ipochi 
> 
> 

What was the reason for these values? Seems that the link of the recording was not shared.
Are there better defaults than 150/10?
