### ISSUE TITLE
Possible race condition, agent attempts to connect to server with  constant churn but never with success

### ISSUE THREAD

**Issue by ipochi** [kubernetes-sigs/apiserver-network-proxy#588]
Example log
```
I0314 16:54:25.600868       1 client.go:210] "Connect to server" serverID="c4cadbb0-f6d4-4a99-b4f3-b9b381073444"
I0314 16:54:25.761272       1 client.go:420] "error dialing backend" error="dial tcp 10.128.0.112:10250: connect: connection refused" dialID=6408280514326081950 connectionID=9953 dialAddress="10.128.0.112:10250"
I0314 16:54:26.150981       1 client.go:420] "error dialing backend" error="dial tcp 10.128.0.104:10250: connect: connection refused" dialID=192523959137244631 connectionID=24866 dialAddress="10.128.0.104:10250"
I0314 16:54:26.710137       1 client.go:210] "Connect to server" serverID="439c099e-7ce3-45e9-bc99-0f98e564916a"
I0314 16:54:27.260388       1 client.go:420] "error dialing backend" error="dial tcp 10.128.0.122:10250: connect: connection refused" dialID=1122099244788874107 connectionID=76141 dialAddress="10.128.0.122:10250"
I0314 16:54:27.493380       1 client.go:420] "error dialing backend" error="dial tcp 10.128.0.126:10250: connect: connection refused" dialID=4464559120374161562 connectionID=76142 dialAddress="10.128.0.126:10250"
I0314 16:54:27.734860       1 client.go:420] "error dialing backend" error="dial tcp 10.128.0.124:20257: connect: connection refused" dialID=3143281958629311892 connectionID=9954 dialAddress="10.128.0.124:20257"
I0314 16:54:27.819654       1 client.go:210] "Connect to server" serverID="c4cadbb0-f6d4-4a99-b4f3-b9b381073444"
I0314 16:54:28.191991       1 client.go:420] "error dialing backend" error="dial tcp 10.128.0.108:10250: connect: connection refused" dialID=8237535106781323853 connectionID=76143 dialAddress="10.128.0.108:10250"
I0314 16:54:28.932535       1 client.go:210] "Connect to server" serverID="ced537b2-2704-4beb-bfbc-6b1d91bf9bd7"
I0314 16:54:29.241984       1 client.go:420] "error dialing backend" error="dial tcp 10.128.0.115:10250: connect: connection refused" dialID=2712513073323874375 connectionID=24867 dialAddress="10.128.0.115:10250"
I0314 16:54:29.424027       1 client.go:420] "error dialing backend" error="dial tcp 10.128.0.122:20257: connect: connection refused" dialID=5407075021300194135 connectionID=9955 dialAddress="10.128.0.122:20257"
I0314 16:54:30.042231       1 client.go:210] "Connect to server" serverID="10d731dc-cddf-4a6a-ac06-3a454f3e36f3"
I0314 16:54:30.168869       1 client.go:420] "error dialing backend" error="dial tcp 10.128.0.108:20257: connect: connection refused" dialID=6340962300391882371 connectionID=9956 dialAddress="10.128.0.108:20257"
I0314 16:54:30.688494       1 client.go:420] "error dialing backend" error="dial tcp 10.128.0.12:10250: connect: connection refused" dialID=3217969276593266815 connectionID=24869 dialAddress="10.128.0.12:10250"
I0314 16:54:30.981938       1 client.go:420] "error dialing backend" error="dial tcp 10.128.0.122:10250: connect: connection refused" dialID=2396106151564997055 connectionID=76144 dialAddress="10.128.0.122:10250"
I0314 16:54:31.149041       1 client.go:210] "Connect to server" serverID="bc5e8a56-9fcf-4504-9ccd-0d94cf20668f"
```

In one of my test clusters I was seeing constant lines of the above in the agent logs with no end. Could there be a potential race condition ?

/cc @jkh52

**Comment by jkh52** [comment]
It looks innocuous to me. Note that all the given logs are Info level, not Error. Which line are you concerned with?

> "Connect to server"

The behavior depends whether you have `--sync-forever` flag, or it could be that some of the 
 (serverCount) konnectivity-server are not fully / successfully allowing agents to connect.

> "error dialing backend"

A direct TCP connection (to serve an apiserver proxy request) to a dial target failed. There is a problem downstream of the agent (try looking at what occupies the given IPv4+port. Is it a Pod or kubelet? Is it unresponsive?).

**Comment by ipochi** [comment]
10250 is kubelet, 20257 is prometheus port for Node Problem Detector and 19100 is for prometheus node exporter

Could be an issue downstream. 

also the `-sync-forever` flag is not enabled.

**Comment by ipochi** [comment]
I've also seen in various cases where the agent has stale metadata about the number of konnectivity-servers it should think there are. 

In that case also there is constant  "Connect to server" serverID="<serverID>"` churn in the logs and the agent is never really able to get updated metadata from the server.

**Comment by jkh52** [comment]
> I've also seen in various cases where the agent has stale metadata about the number of konnectivity-servers it should think there are.

In the agent sync loop, it will trust the last-seen serverCount. So staleness should only arise if a konnectivity-server with a stale value has not been restarted with new --server-count. (Remember that server does not yet support dynamic count).

> In that case also there is constant "Connect to server" serverID=""` churn in the logs and the agent is never really able to get updated metadata from the server.

In my experience empty serverID always turns out to be auth token review failure.

**Comment by jkh52** [comment]
Tentatively closing, there is a plausible explanation.
