### ISSUE TITLE
No container image for v0.28.5

### ISSUE THREAD

**Issue by guettli** [kubernetes-sigs/apiserver-network-proxy#611]
There is no container image for [v0.28.5](https://github.com/kubernetes-sigs/apiserver-network-proxy/releases/tag/v0.28.5) yet

https://explore.ggcr.dev/?repo=registry.k8s.io%2Fkas-network-proxy%2Fproxy-server

![image](https://github.com/kubernetes-sigs/apiserver-network-proxy/assets/414336/0f2673bb-2862-4f30-8074-05f0d78ff301)

The image for proxy-agent is missing, too:

https://explore.ggcr.dev/?repo=registry.k8s.io%2Fkas-network-proxy%2Fproxy-agent

Or am I missing something?

**Comment by liangyuanpeng** [comment]
@guettli 

it's available now.

```shell
$ docker pull registry.k8s.io/kas-network-proxy/proxy-server:v0.28.5
v0.28.5: Pulling from kas-network-proxy/proxy-server
6b16ad2aede1: Pull complete 
fe5ca62666f0: Pull complete 
be1681d2fb7c: Pull complete 
0f8b424aa0b9: Pull complete 
d557676654e5: Pull complete 
c8022d07192e: Pull complete 
d858cbc252ad: Pull complete 
1069fc2daed1: Pull complete 
4aa0ea1413d3: Pull complete 
5318d93a3a65: Pull complete 
307c1adadb60: Pull complete 
7717c731a205: Pull complete 
Digest: sha256:a77b1b9a58f83e5e891df0dbf86813d12293a1c89d07182c554c463132c41c81
Status: Downloaded newer image for registry.k8s.io/kas-network-proxy/proxy-server:v0.28.5
registry.k8s.io/kas-network-proxy/proxy-server:v0.28.5
```
