### ISSUE TITLE
Include docker build as part of CI

### ISSUE THREAD

**Issue by Jefftree** [kubernetes-sigs/apiserver-network-proxy#64]
https://k8s-testgrid.appspot.com/sig-cloud-provider-apiserver-network-proxy#apiserver-network-proxy-push-images

The above tests only runs on the master branch, and we only get failure notifications in hindsight of a PR merge. If a PR could cause the build and push procedure to fail, we should catch that before it is merged. I think we should at least run docker build on all PRs as part of the CI process

/cc @Sh4d1

**Comment by Sh4d1** [comment]
@Jefftree yep right, I'll try to add the docker build to the prow job tomorrow!
