### ISSUE TITLE
Clean up UDS file before listening

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes-sigs/apiserver-network-proxy#69]
When the proxy server restarts, if the UDS file already exists, trying to listen on the socket will fail with "bind: address already in use". The server should delete the file if it exists, and then listen to the socket.

cc @Jefftree

**Comment by Jefftree** [comment]
When does this happen? The socket binding should be automatically removed if the proxy server is shut down. I'm hesitant to just delete to file since it's possible that things were misconfigured, and we're forcefully removing a random file that the user specified.

**Comment by cheftako** [comment]
I believe that at least one of the places (for the http-connect case) which cleans up the UDS file is https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/master/cmd/proxy/main.go#L395 (defer func() {udsListener.Close()}()). For the grpc case I would guess its the GracefulStop result but calling that method seems less bullet proof.

**Comment by caesarxuchao** [comment]
If the proxy server crashes, then no one is going to cleanup the uds file. This happened to me today.

As a side note, we need to check udsListener is nil before call udsListener.Close().

**Comment by Jefftree** [comment]
I encountered this quite often while simulating error conditions. Will send out a fix

/assign
