### ISSUE TITLE
use of closed network connection

### ISSUE THREAD

**Issue by Jefftree** [kubernetes-sigs/apiserver-network-proxy#70]
I'm constantly seeing this message (from the proxy server logs when using http-connect), even when running the proxy server/agent locally: 

```
Received error on connection read unix konnectivity-server.socket->@: use of closed network connection. 
```

It doesn't have any effect on the proxy/data transfer as far as the client is concerned, but seems to be some clean up we may not be doing.

/cc @cheftako 
/cc @caesarxuchao 

To repro, start 4 processes in the terminal:

It seems to occur in almost every request.
```
python -m SimpleHTTPServer 8001

./bin/proxy-server --uds-name=konnectivity-server.socket --mode=http-connect --cluster-cert=certs/agent/issued/proxy-master.crt --cluster-key=certs/agent/private/proxy-master.key --server-port=0

./bin/proxy-agent --ca-cert=certs/agent/issued/ca.crt --agent-cert=certs/agent/issued/proxy-agent.crt --agent-key=certs/agent/private/proxy-agent.key

./bin/proxy-test-client --proxy-uds=konnectivity-server.socket --proxy-host= --proxy-port=0 --mode=http-connect --request-port=8001 --request-host=localhost 
```

**Comment by caesarxuchao** [comment]
Which component prints the error message?

**Comment by Jefftree** [comment]
Proxy server. Updated the original message.

**Comment by caesarxuchao** [comment]
#80 is a dup of this issue. https://github.com/kubernetes-sigs/apiserver-network-proxy/issues/80#issuecomment-594971589 explained why this happened. This is a red-herring, we need to improve the logging.

**Comment by Jefftree** [comment]
Actually I think this is due to the connection being closed twice in HTTP connect mode.

https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/master/pkg/server/tunnel.go#L100

and

https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/master/pkg/server/server.go#L53

We're attempting to call close on an already closed connection. I'm not sure if this is a bug or expected because the two operations are on separate go routines and the connection can also be closed from either the source or the destination can send the close req/rsp.
