### ISSUE TITLE
[GRPC Mode] Client -> Proxy connections should be closed when finished

### ISSUE THREAD

**Issue by Jefftree** [kubernetes-sigs/apiserver-network-proxy#86]
When running in GRPC mode,  client -> proxy UDS connections are not closed after the (client -> proxy server -> agent -> destination) connection is closed. After a `CLOSE_RSP` It seems that we only remove the frontends, but never call close on the underlying GRPC stream between the client and proxy. This causes resource leaks.

Should be an easy fix though.

After just a couple of operations on the master, the number of opened streams can get quite high. This does not happen in http-connect mode.

```
jying@kubernetes-master ~ $ netstat | grep konnectivity-server.socket | wc -l
204
```

/cc @caesarxuchao

**Comment by caesarxuchao** [comment]
The fix should be in k/k?

**Comment by Jefftree** [comment]
We should be able to close a stream from either end. It'll probably be more convenient to implement this on the server side.

**Comment by caesarxuchao** [comment]
#93 was a temporary solution. I think @Jefftree is working on a more thorough solution. Let's keep this bug open in the meantime.

**Comment by Jefftree** [comment]
After performance testing with reusing connections/streams, I think the final verdict is that we'll keep the current 1 dial = 1 connection mapping.
