### ISSUE TITLE
CI for both httpConnect and grpc mode

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes-sigs/apiserver-network-proxy#88]
Currently our [CI](https://k8s-testgrid.appspot.com/sig-api-machinery-network-proxy#ci-kubernetes-e2e-gci-gce-network-proxy) only supports the grpc mode. We need to figure out a way to continuously test both mdoes.

**Comment by Jefftree** [comment]
This has been completed: https://k8s-testgrid.appspot.com/sig-api-machinery-network-proxy#Summary

/close
